<?php
/**
 * Shortcode Map For Counter 
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Counter  */
/*-----------------------------------------------------------------------------------*/

  vc_map( 
    array(
    'name' => esc_html__( 'Counter', 'hongo-addons'),
    'base' => 'hongo_counter_or_skill',
    'category' => 'Hongo',
    'description' => esc_html__( 'Statistics counter', 'hongo-addons' ),
    'icon' => 'fa-regular fa-clock hongo-shortcode-icon', //URL or CSS class with icon image.
    'params' => array(
      array(
        'type' => 'dropdown',
        'holder' => 'div',
        'class' => '',
        'heading' => esc_html__( 'Style', 'hongo-addons'),
        'param_name' => 'hongo_counter_style',
        'value' => array(esc_html__( 'Select', 'hongo-addons') => '',
                         esc_html__( 'Style 1', 'hongo-addons') => 'counter-style1',
                         esc_html__( 'Style 2', 'hongo-addons') => 'counter-style2',
                         esc_html__( 'Style 3', 'hongo-addons') => 'counter-style3',
                        ),
      ),
      array(
        'type' => 'hongo_preview_image',
        'heading' => esc_html__( 'Select pre-made style', 'hongo-addons'),
        'param_name' => 'hongo_counter_skill_preview_image',
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Custom icon image', 'hongo-addons'),
        'param_name' => 'custom_icon',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0',
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2' ) ),
      ),
      array(
        'type' => 'attach_image',
        'heading' => esc_html__( 'Custom image', 'hongo-addons'),
        'param_name' => 'custom_icon_image',
        'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
        'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'hongo-addons' ),
      ),
      array(
        'type' => 'textfield',
        'heading' => esc_html__( 'Icon image maximum width', 'hongo-addons' ),
        'param_name' => 'custom_icon_max_width',
        'value' => '',
        'dependency'  => array( 'element' => 'custom_icon', 'value' => array( '1' ) ),
        'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
      ),
      array(
        'type' => 'hongo_icon',
        'heading' => esc_html__( 'Icon', 'hongo-addons'),
        'param_name' => 'counter_icon',
        'admin_label' => true,
        'value' => '',
        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
      ),
      array(
        'type' => 'textfield',
        'heading' =>esc_html__( 'Counter number', 'hongo-addons'),
        'param_name' => 'counter_number',
        'admin_label' => true,
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'textfield',
        'heading' => esc_html__( 'Number postfix', 'hongo-addons'),
        'param_name' => 'number_postfix',
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'textfield',
        'heading' => esc_html__( 'Title', 'hongo-addons'),
        'param_name' => 'title',
        'admin_label' => true,
        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => esc_html__( 'Counting duration', 'hongo-addons'),
        'param_name' => 'hongo_counter_animation_duration',
        'admin_label' => true,
        'value' => array(esc_html__( 'Default', 'hongo-addons') => '',
                         esc_html__( '1000ms', 'hongo-addons') => '1000',
                         esc_html__( '2000ms', 'hongo-addons') => '2000',
                         esc_html__( '3000ms', 'hongo-addons') => '3000',
                         esc_html__( '4000ms', 'hongo-addons') => '4000',
                         esc_html__( '5000ms', 'hongo-addons') => '5000',
                         esc_html__( '6000ms', 'hongo-addons') => '6000',
                         esc_html__( '7000ms', 'hongo-addons') => '7000',
                        ),
        'std' => '2000',
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
          
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Link on text', 'hongo-addons'),
        'param_name' => 'hongo_enable_link',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => esc_html__( 'Link target', 'hongo-addons'),
        'param_name' => 'hongo_link_target',
        'value' => array(esc_html__('Self', 'hongo-addons') => '_self', 
                           esc_html__('New tab / window', 'hongo-addons') => '_blank',
                           esc_html__('One page', 'hongo-addons') => 'one_page',
                          ),
        'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
      ),
      array(
        'type' => 'dropdown',
        'heading' =>esc_html__( 'Add link on', 'hongo-addons'),
        'param_name' => 'hongo_link_on',
        'admin_label' => true,
        'value' => array( esc_html__( 'Select','hongo-addons') => '',
                          esc_html__( 'Icon','hongo-addons') => 'icon',
                          esc_html__( 'Counter','hongo-addons') => 'counter',
                          esc_html__( 'Title','hongo-addons') => 'title',
                          esc_html__( 'All','hongo-addons') => 'all',
                        ),
        'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
      ),
      array(
        'type' => 'textfield',
        'heading' =>esc_html__( 'Link / URL', 'hongo-addons'),
        'param_name' => 'hongo_link_url',
        'admin_label' => true,
        'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
        'description' => esc_html__( 'Enter full URL with http, like http://www.example.com', 'hongo-addons' ),
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => esc_html__( 'Link hover color', 'hongo-addons' ),
        'param_name' => 'hongo_link_hover_color',
        'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Border', 'hongo-addons'),
        'param_name' => 'hongo_enable_border',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'std' => '1',
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1' ) ),
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Separator', 'hongo-addons'),
        'param_name' => 'hongo_enable_separator',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'std' => '1',
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style2','counter-style3' ) )
      ),
      array(
        'type' => 'animation_style',
        'heading' => esc_html__( 'Animation', 'hongo-addons' ),
        'param_name' => 'initial_loading_animation',
        'value' => '',
        'settings' => array(
          'type' => array(
            'in',
            'other',
          ),
        ),
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
        'description' => __( 'Select type of animation for element to be animated when it "enters" the browsers viewport (Note: works only in modern browsers).', 'hongo-addons' ),
      ),
      array(
        'type' => 'textfield',
        'heading' => esc_html__( 'Animation duration', 'hongo-addons' ),
        'param_name' => 'hongo_animation_duration',
        'dependency' => array( 'element' => 'initial_loading_animation', 'value_not_equal_to' => array( 'none' ) ),
        'description' => esc_html__( 'Add animation duration in mls, like 200', 'hongo-addons' ),        
      ),
      array(
        'type' => 'dropdown',
        'heading' => esc_html__( 'Icon size', 'hongo-addons'),
        'param_name' => 'hongo_counter_icon_size',
        'admin_label' => true,
        'value' => array( esc_html__( 'Default','hongo-addons') => '',
                          esc_html__( 'Extra large','hongo-addons') => 'icon-extra-large', 
                          esc_html__( 'Large','hongo-addons') => 'icon-large',
                          esc_html__( 'Extra medium','hongo-addons') => 'icon-extra-medium',
                          esc_html__( 'Medium','hongo-addons') => 'icon-medium',
                          esc_html__( 'Small','hongo-addons') => 'icon-small',
                          esc_html__( 'Extra small','hongo-addons') => 'icon-extra-small',
                        ),
        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => esc_html__( 'Icon color', 'hongo-addons' ),
        'param_name' => 'hongo_icon_color',
        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => esc_html__( 'Icon hover color', 'hongo-addons' ),
        'param_name' => 'hongo_icon_hover_color',
        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),
      array(
        'type' => 'textfield',
        'class' => '',
        'heading' => esc_html__( 'Box hover border thickness', 'hongo-addons' ),
        'param_name' => 'hongo_box_hover_border_size',
        'dependency' => array( 'element' => 'hongo_enable_border', 'value' => array( '1' ) ),
        'description' => esc_html__( 'In pixel like 2px', 'hongo-addons' ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => esc_html__( 'Box hover border color', 'hongo-addons' ),
        'param_name' => 'hongo_box_hover_border_color',
        'dependency' => array( 'element' => 'hongo_enable_border', 'value' => array('1') ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),
      array(
        'type' => 'colorpicker',
        'class' => '',
        'heading' => esc_html__( 'Separator color', 'hongo-addons' ),
        'param_name' => 'hongo_separator_color',
        'dependency' => array( 'element' => 'hongo_enable_separator', 'value' => array('1') ),
        'group' => esc_html__( 'Style', 'hongo-addons' ),
      ),

      array(
        'type'        => 'responsive_font_settings',
        'param_name'  => 'hongo_font_counter_setting',
        'heading'     => esc_html__( 'Counter/number typography', 'hongo-addons' ),
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
        'hide_element_keys' => array( 'text-hover-color', 'font-transform' ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => esc_html__( 'Counter element tag', 'hongo-addons'),
        'param_name' => 'hongo_counter_element_tag',
        'value' => $hongo_element_tag,
        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Use additional font for counter', 'hongo-addons'),
        'param_name' => 'hongo_enable_counter_alternate_font',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
        'std' => '1',
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
        'description'=> esc_html__( 'If On is selected then counter will use additional font family setup in WordPress customizer', 'hongo-addons' ),
      ),
      array(
        'type'        => 'responsive_font_settings',
        'param_name'  => 'hongo_font_title_setting',
        'heading'     => esc_html__( 'Title typography', 'hongo-addons' ),
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
        'hide_element_keys' => array( 'text-hover-color' ),
      ),
      array(
        'type' => 'dropdown',
        'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
        'param_name' => 'hongo_title_element_tag',
        'value' => $hongo_element_tag,
        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency' => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
      ),
      array(
        'type' => 'hongo_custom_switch_option',
        'heading' => esc_html__( 'Use additional font for title', 'hongo-addons'),
        'param_name' => 'hongo_enable_title_alternate_font',
        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                         esc_html__( 'On', 'hongo-addons') => '1'
                        ),
        'std' => '1',
        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
        'group' => esc_html__( 'Typography', 'hongo-addons' ),
        'dependency'  => array( 'element' => 'hongo_counter_style', 'value' => array( 'counter-style1', 'counter-style2', 'counter-style3' ) ),
        'description'=> esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
      ),
      $hongo_vc_extra_id,
      $hongo_vc_extra_class,
      ),
    ) 
  );