<?php
/**
 * Shortcode Map For Testimonial Slider
 *
 * @package hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Testimonial Slider */
/*-----------------------------------------------------------------------------------*/

vc_map( 
    array(
        'name' => esc_html__( 'Testimonial Slider', 'hongo-addons' ),
        'base' => 'hongo_testimonial_slider',
        'description' => esc_html__( 'Clients testimonial slider', 'hongo-addons' ),
        'icon' => 'fa-solid fa-arrows-alt-h hongo-shortcode-icon',
        'category' => 'Hongo',
        'params' => array(
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons'),
                'param_name' => 'hongo_testimonial_slider_style',
                'admin_label' => true,
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons') => 'testimonial-slider-style-1',
                    esc_html__( 'Style 2', 'hongo-addons') => 'testimonial-slider-style-2',
                    esc_html__( 'Style 3', 'hongo-addons') => 'testimonial-slider-style-3',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__('Select pre-made style for testimonial slider', 'hongo-addons'),
                'param_name' => 'hongo_slider_preview_image',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Round image', 'hongo-addons' ),
                'param_name' => 'round_image',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1','testimonial-slider-style-2','testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'param_group',
                'param_name' => 'hongo_testimonial_slides',
                'heading' => esc_html__( 'Slide', 'hongo-addons' ),
                'value' => '',
                'params' => array(
                    array(
                        'type' => 'attach_image',
                        'heading' => esc_html__( 'Image', 'hongo-addons' ),
                        'param_name' => 'hongo_image',
                        'description' => esc_html__( 'Your image will look impressive when image is in a square shape.', 'hongo-addons' )
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                        'param_name' => 'hongo_image_srcset',
                        'value' => hongo_get_thumbnail_image_sizes(),
                        'std' => 'full',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Name', 'hongo-addons'),
                        'param_name' => 'hongo_name',
                        'admin_label' => true,
                        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Designation', 'hongo-addons'),
                        'param_name' => 'hongo_designation',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Title', 'hongo-addons' ),
                        'param_name'  => 'hongo_title_content',
                        'description' => esc_html__( 'Only use for style 1', 'hongo-addons' ),
                    ),
                    array(
                        'type' => 'textarea',
                        'heading' => esc_html__( 'Content', 'hongo-addons'),
                        'param_name' => 'hongo_content',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Rating', 'hongo-addons'),
                        'param_name' => 'hongo_slide_rating',
                        'value' => array(
                            esc_html__( 'Select', 'hongo-addons') => '',
                            esc_html__( '1', 'hongo-addons') => '1',
                            esc_html__( '2', 'hongo-addons') => '2',
                            esc_html__( '3', 'hongo-addons') => '3',
                            esc_html__( '4', 'hongo-addons') => '4',
                            esc_html__( '5', 'hongo-addons') => '5',
                            ),
                        'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                        'description' => esc_html__( 'Use only for style 2', 'hongo-addons' ),
                    ),
                ),
                'callbacks' => array(
                    'after_add' => 'vcChartParamAfterAddCallback',
                ),
                'group' => esc_html__( 'Slides', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2','testimonial-slider-style-3' ) 
                ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Pagination', 'hongo-addons'),
                'param_name' => 'show_pagination',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select ON to show pagination in slider', 'hongo-addons' ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Pagination style', 'hongo-addons' ),
                'param_name' => 'show_pagination_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Dot style', 'hongo-addons') => 'swiper-pagination-dots',
                    esc_html__( 'Line style', 'hongo-addons') => 'swiper-pagination-square',
                    esc_html__( 'Dot border style', 'hongo-addons') => 'swiper-pagination-border',
                ),
                'dependency' => array( 'element' => 'show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_active_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Navigation', 'hongo-addons'),
                'param_name' => 'show_navigation',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                    ),
                'std' => '1',
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-3' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Navigation color', 'hongo-addons' ),
                'param_name' => 'hongo_navigation_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'show_navigation', 'value' => array('1') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Cursor color style', 'hongo-addons'),
                'param_name' => 'show_cursor_color_style',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'White cursor', 'hongo-addons') => 'white-move',
                    esc_html__( 'Black cursor', 'hongo-addons') => 'black-move',
                    esc_html__( 'Default cursor', 'hongo-addons') => 'cursor-default',
                    ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Transition speed', 'hongo-addons'),
                'param_name' => 'slidespeed',
                'value' => '',
                'description' => esc_html__( 'Enter slide speed time like 500, where 1000 = 1 second', 'hongo-addons'),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Autoplay', 'hongo-addons'),
                'param_name' => 'autoplay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                    ),
                'std' => '1',
                'description' => esc_html__( 'Select On to autoplay slider', 'hongo-addons' ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Slide delay', 'hongo-addons'),
                'param_name' => 'slidedelay',
                'value' => '',
                'description' => esc_html__( 'Enter delay time (before switching to other slide) like 500, where 1000 = 1 second', 'hongo-addons'),
                'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Loop', 'hongo-addons'),
                'param_name' => 'autoloop',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                    ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in desktop', 'hongo-addons'),
                'param_name' => 'slides_per_view_desktop',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '3',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mini desktop', 'hongo-addons'),
                'param_name' => 'slides_per_view_mini_desktop',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '3',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in tablet', 'hongo-addons'),
                'param_name' => 'slides_per_view_tablet',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '2',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mobile', 'hongo-addons'),
                'param_name' => 'slides_per_view_mobile',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '1',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_background_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1','testimonial-slider-style-2','testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active box background color', 'hongo-addons' ),
                'param_name' => 'hongo_active_box_background_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Border', 'hongo-addons' ),
                'param_name' => 'enable_border',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-2','testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Border width', 'hongo-addons'),
                'param_name' => 'border_width',
                'group' => esc_html__( 'Style', 'hongo-addons'),
                'dependency' => array( 'element' => 'enable_border', 'value' => array('1') ),
                'description' => esc_html__( 'In pixel like 2px', 'hongo-addons'),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Border style', 'hongo-addons' ),
                'param_name' => 'border_style',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Solid', 'hongo-addons') => 'solid',
                    esc_html__( 'Dotted', 'hongo-addons') => 'dotted',
                    esc_html__( 'Dashed', 'hongo-addons') => 'dashed',
                    esc_html__( 'None', 'hongo-addons') => 'none',
                    esc_html__( 'Hidden', 'hongo-addons') => 'hidden',
                    esc_html__( 'Double', 'hongo-addons') => 'double',
                    esc_html__( 'Groove', 'hongo-addons') => 'groove',
                    esc_html__( 'Ridge', 'hongo-addons') => 'ridge',
                    esc_html__( 'Inset', 'hongo-addons') => 'inset',
                    esc_html__( 'Outset', 'hongo-addons') => 'outset',
                    esc_html__( 'Initial', 'hongo-addons') => 'initial',
                    esc_html__( 'Inherit', 'hongo-addons') => 'inherit',
                ),
                'dependency' => array( 'element' => 'enable_border', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Border color', 'hongo-addons' ),
                'param_name' => 'border_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'enable_border', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Rating color', 'hongo-addons' ),
                'param_name' => 'rating_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-2' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Border radius', 'hongo-addons'),
                'param_name' => 'border_radius',
                'group' => esc_html__( 'Style', 'hongo-addons'),
                'dependency' => array( 'element' => 'enable_border', 'value' => array('1') ),
                'description' => esc_html__( 'In pixel like 2px', 'hongo-addons'),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_name_setting',
                'heading'     => esc_html__( 'Name typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons'),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Name element tag', 'hongo-addons'),
                'param_name' => 'name_heading_tag',
                'value' => $hongo_element_tag,
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for name', 'hongo-addons' ),
                'param_name' => 'additional_font_name',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then name will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_designation_setting',
                'heading'     => esc_html__( 'Designation typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons'),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Designation element tag', 'hongo-addons'),
                'param_name' => 'designation_heading_tag',
                'value' => $hongo_element_tag,
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for designation', 'hongo-addons' ),
                'param_name' => 'additional_font_designation',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then designation will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_title_setting',
                'heading'     => esc_html__( 'Title typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons'),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'title_heading_tag',
                'value' => $hongo_element_tag,
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for title', 'hongo-addons' ),
                'param_name' => 'additional_font_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_content_setting',
                'heading'     => esc_html__( 'Content typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons'),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for content', 'hongo-addons' ),
                'param_name' => 'additional_font_content',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-left-setting typography-full-setting',
                'description' => esc_html__( 'If On is selected then content will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_testimonial_slider_style', 'value' => array( 'testimonial-slider-style-1', 'testimonial-slider-style-2', 'testimonial-slider-style-3' ) ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Element ID', 'hongo-addons' ),
                'description' => sprintf( esc_html__( 'Enter element ID (Note: make sure it is unique and valid according to %s).', 'hongo-addons'), '<a target="_blank" href="https://www.w3schools.com/tags/att_global_id.asp">w3c specification</a>'),
                'param_name'  => 'hongo_slider_id',
                'group'       => esc_html__( 'Extras', 'hongo-addons' )
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Extra class name', 'hongo-addons' ),
                'description' => esc_html__( 'Add additional CSS class to this element, you can define multiple CSS class with use of space like "Class1 Class2". You can write css code using this class and add it in customizer or your child theme css file.', 'hongo-addons' ),
                'param_name'  => 'hongo_slider_class',
                'group'       => esc_html__( 'Extras', 'hongo-addons' )
            ),
        ),
    )
);