<?php
/**
 * Map For Social Icon
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Social Icon */
/*-----------------------------------------------------------------------------------*/

vc_map( 
    array(
        'icon' => 'hongo-shortcode-icon fa-solid fa-stop',
        'name' => esc_html__('Social Icons', 'hongo-addons'),
        'description' => esc_html__( 'Add your social profiles', 'hongo-addons' ),
        'base' => 'hongo_social',
        'category' => 'Hongo',
        'content_element' => true,
        'params' => array(
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Style', 'hongo-addons'),
                'param_name' => 'hongo_social_style',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons') => 'social-icon-style-1',
                    esc_html__( 'Style 2', 'hongo-addons') => 'social-icon-style-2',
                    esc_html__( 'Style 3', 'hongo-addons') => 'social-icon-style-3',
                    esc_html__( 'Style 4', 'hongo-addons') => 'social-icon-style-4',
                    esc_html__( 'Style 5', 'hongo-addons') => 'social-icon-style-5',
                    esc_html__( 'Style 6', 'hongo-addons') => 'social-icon-style-6',
                    esc_html__( 'Style 7', 'hongo-addons') => 'social-icon-style-7',
                    esc_html__( 'Style 8', 'hongo-addons') => 'social-icon-style-8',
                    esc_html__( 'Style 9', 'hongo-addons') => 'social-icon-style-9',
                    esc_html__( 'Style 10', 'hongo-addons') => 'social-icon-style-10',
                    esc_html__( 'Style 11', 'hongo-addons') => 'social-icon-style-11',
                    esc_html__( 'Style 12', 'hongo-addons') => 'social-icon-style-12',
                    esc_html__( 'Style 13', 'hongo-addons') => 'social-icon-style-13',
                    esc_html__( 'Style 14', 'hongo-addons') => 'social-icon-style-14',
                    esc_html__( 'Style 15', 'hongo-addons') => 'social-icon-style-15',
                ),
            ),  
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__('Select pre-made style', 'hongo-addons'),
                'param_name' => 'hongo_social_preview_image',
            ),
            array(
                'type'        => 'hongo_custom_social_sorting',
                'heading'     => esc_html__( 'Social icon order', 'hongo-addons'),
                'param_name'  => 'hongo_social_sorting',
                'value'       => array(
                    esc_html__( 'Facebook', 'hongo-addons')      => 'facebook',
                    esc_html__( 'Twitter', 'hongo-addons')       => 'twitter',
                    esc_html__( 'Dribbble', 'hongo-addons')      => 'dribbble',
                    esc_html__( 'LinkedIn', 'hongo-addons')      => 'linkedin',
                    esc_html__( 'Instagram', 'hongo-addons')     => 'instagram',
                    esc_html__( 'Tumblr', 'hongo-addons')        => 'tumblr',
                    esc_html__( 'Pinterest', 'hongo-addons')     => 'pinterest',
                    esc_html__( 'Youtube', 'hongo-addons')       => 'youtube',
                    esc_html__( 'Vimeo', 'hongo-addons')         => 'vimeo',
                    esc_html__( 'Soundcloud', 'hongo-addons')    => 'soundcloud',
                    esc_html__( 'Flickr', 'hongo-addons')        => 'flickr',
                    esc_html__( 'RSS', 'hongo-addons')           => 'rss',
                    esc_html__( 'Reddit', 'hongo-addons')        => 'reddit',
                    esc_html__( 'Behance', 'hongo-addons')       => 'behance',
                    esc_html__( 'Vine', 'hongo-addons')          => 'vine',
                    esc_html__( 'GitHub', 'hongo-addons')        => 'github',
                    esc_html__( 'Xing', 'hongo-addons')          => 'xing',
                    esc_html__( 'VK', 'hongo-addons')            => 'vk',
                    esc_html__( 'Yelp', 'hongo-addons')          => 'yelp',
                    esc_html__( 'Discord', 'hongo-addons')       => 'discord',
                    esc_html__( 'Email address', 'hongo-addons') => 'email',
                    esc_html__( 'Skype', 'hongo-addons')         => 'skype',
                ),
                'std' => '',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Facebook URL', 'hongo-addons'),
                'param_name' => 'hongo_fb_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Twitter URL', 'hongo-addons'),
                'param_name' => 'hongo_tw_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Dribbble URL', 'hongo-addons'),
                'param_name' => 'hongo_db_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Linkedin URL', 'hongo-addons'),
                'param_name' => 'hongo_li_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Instagram URL', 'hongo-addons'),
                'param_name' => 'hongo_ig_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Tumblr URL', 'hongo-addons'),
                'param_name' => 'hongo_tb_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Pinterest URL', 'hongo-addons'),
                'param_name' => 'hongo_pi_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('YouTube URL', 'hongo-addons'),
                'param_name' => 'hongo_yt_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Vimeo URL', 'hongo-addons'),
                'param_name' => 'hongo_vm_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Soundcloud URL', 'hongo-addons'),
                'param_name' => 'hongo_sc_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Flickr URL', 'hongo-addons'),
                'param_name' => 'hongo_fk_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('RSS URL', 'hongo-addons'),
                'param_name' => 'hongo_rss_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Reddit URL', 'hongo-addons'),
                'param_name' => 'hongo_rd_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Behance URL', 'hongo-addons'),
                'param_name' => 'hongo_bh_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Vine URL', 'hongo-addons'),
                'param_name' => 'hongo_vine_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('GitHub URL', 'hongo-addons'),
                'param_name' => 'hongo_gh_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Xing URL', 'hongo-addons'),
                'param_name' => 'hongo_xing_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('VK URL', 'hongo-addons'),
                'param_name' => 'hongo_vk_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Yelp URL', 'hongo-addons'),
                'param_name' => 'hongo_yelp_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Discord URL', 'hongo-addons'),
                'param_name' => 'hongo_discord_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Email address', 'hongo-addons'),
                'param_name' => 'hongo_email_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Skype URL', 'hongo-addons'),
                'param_name' => 'hongo_skype_url',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),

            array(
                'type' => 'textarea_raw_html',
                'heading' => esc_html__( 'Custom icons code', 'hongo-addons' ),
                'value'      => base64_encode( 'CustomHTML' ),
                'param_name' => 'hongo_custom_link',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'animation_style',
                'heading' => esc_html__( 'Animation', 'hongo-addons' ),
                'param_name' => 'hongo_animation_style',
                'value' => '',
                'settings' => array(
                  'type' => array(
                    'in',
                    'other',
                  ),
                ),
                'description' => __( 'Select type of animation for element to be animated when it "enters" the browsers viewport (Note: works only in modern browsers).', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Animation duration', 'hongo-addons' ),
                'param_name' => 'hongo_animation_duration',
                'dependency' => array( 'element' => 'hongo_animation_style', 'value_not_equal_to' => array( 'none' ) ),
                'description' => esc_html__( 'Add animation duration in mls, like 200', 'hongo-addons' ),              
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Text case', 'hongo-addons'),
                'param_name' => 'hongo_text_case',
                'value' => array(
                            esc_html__( 'Default', 'hongo-addons' ) => '',
                            esc_html__( 'Capitalize', 'hongo-addons' ) => 'capitalize',
                            esc_html__( 'Lowercase', 'hongo-addons' ) => 'lowercase',
                            esc_html__( 'Uppercase', 'hongo-addons' ) => 'uppercase',
                            esc_html__( 'None', 'hongo-addons' ) => 'none',
                        ),
                'std' => '_blank',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-8','social-icon-style-14','social-icon-style-15') ),
            ), 
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Link target', 'hongo-addons'),
                'param_name' => 'hongo_link_target',
                'value' => array(
                    esc_html__('Self', 'hongo-addons') => '_self', 
                    esc_html__('New tab / window', 'hongo-addons') => '_blank',
                ),
                'std' => '_blank',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ), 
            array(
                'type' => 'textfield',
                'heading' => esc_html__('Space between icons', 'hongo-addons'),
                'param_name' => 'space_between_gap',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'description' => esc_html__( 'In pixel like 2px', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Icon size', 'hongo-addons'),
                'param_name' => 'hongo_icon_type',
                'value' => array(
                    esc_html__('Select', 'hongo-addons') => '',
                    esc_html__('Extra large', 'hongo-addons') => 'extra-large-icon',
                    esc_html__('Large', 'hongo-addons') => 'large-icon',
                    esc_html__('Medium', 'hongo-addons') => 'medium-icon',
                    esc_html__('Small', 'hongo-addons') => 'small-icon',
                    esc_html__('Extra small', 'hongo-addons') => 'extra-small-icon',
                    esc_html__('Very small', 'hongo-addons') => 'very-small-icon',
                ),
                'std' => 'small-icon',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array('social-icon-style-1','social-icon-style-2','social-icon-style-3','social-icon-style-4','social-icon-style-5','social-icon-style-6','social-icon-style-7','social-icon-style-8','social-icon-style-9','social-icon-style-10','social-icon-style-11','social-icon-style-12','social-icon-style-13','social-icon-style-14','social-icon-style-15') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for label', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_label',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-8' ,'social-icon-style-14','social-icon-style-15' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon background color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_bg_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-6','social-icon-style-10','social-icon-style-11' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon background hover color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_bg_hover_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-11' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Text color', 'hongo-addons' ),
                'param_name' => 'hongo_text_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-8' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-1', 'social-icon-style-4', 'social-icon-style-5', 'social-icon-style-6', 'social-icon-style-7', 'social-icon-style-8','social-icon-style-9' ,'social-icon-style-11','social-icon-style-13','social-icon-style-15' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon hover color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_hover_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-3', 'social-icon-style-4', 'social-icon-style-6','social-icon-style-10','social-icon-style-11' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon hover color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_clip_hover_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-12' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Border color', 'hongo-addons' ),
                'param_name' => 'hongo_border_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-9','social-icon-style-11','social-icon-style-13' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Border hover color', 'hongo-addons' ),
                'param_name' => 'hongo_border_hover_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-3' ,'social-icon-style-11') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Separator color', 'hongo-addons' ),
                'param_name' => 'hongo_separator_color',
                'dependency'  => array( 'element' => 'hongo_social_style', 'value' => array( 'social-icon-style-14' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        )
    ) 
);