<?php
/**
 * Map For Newsletter
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Newsletter */
/*-----------------------------------------------------------------------------------*/

vc_map( 
    array(
        'name' => esc_html__( 'Newsletter', 'hongo-addons' ),
        'base' => 'hongo_newsletter',
        'category' => 'Hongo',
        'description' => esc_html__( 'Newsletter subscription block', 'hongo-addons' ),
        'icon' => 'fa-regular fa-envelope hongo-shortcode-icon', //URL or CSS class with icon image.
        'params' => array(
            array(
                'type'        => 'dropdown',
                'heading'     => esc_html__( 'Style', 'hongo-addons' ),
                'param_name'  => 'hongo_newsletter_style',
                'admin_label' => true,
                'value'       => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons')  => 'hongo-content-newsletter-1',
                    esc_html__( 'Style 2', 'hongo-addons')  => 'hongo-content-newsletter-2',
                    esc_html__( 'Style 3', 'hongo-addons')  => 'hongo-content-newsletter-3',
                    esc_html__( 'Style 4', 'hongo-addons')  => 'hongo-content-newsletter-4',
                    esc_html__( 'Style 5', 'hongo-addons')  => 'hongo-content-newsletter-5',
                    esc_html__( 'Style 6', 'hongo-addons')  => 'hongo-content-newsletter-6',
                ),
            ),
            array(
                'type'       => 'hongo_preview_image',
                'heading'    => esc_html__( 'Select pre-made style for Shop Banner', 'hongo-addons'),
                'param_name' => 'hongo_newsletter_preview_image',
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Title', 'hongo-addons'),
                'param_name' => 'hongo_title',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'description'=> esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Subtitle', 'hongo-addons'),
                'param_name' => 'hongo_subtitle',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type'       => 'textarea_html',
                'heading'    => esc_html__( 'Content', 'hongo-addons' ),
                'param_name' => 'content',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
            ),
            array(
                'type'       => 'textarea',
                'heading'    => esc_html__( 'Mailchimp / other shortcode or custom code', 'hongo-addons'),
                'param_name' => 'hongo_shortcode_id',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'description'=> esc_html__( 'Note: Custom css or style needs to be implemented for any other form except Mailchimp', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_width',
                'heading' => esc_html__( 'Content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_mini_width',
                'heading' => esc_html__( 'Content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_ipad_width',
                'heading' => esc_html__( 'Content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_mobile_width',
                'heading' => esc_html__( 'Content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Subtitle background color', 'hongo-addons'),
                'param_name' => 'hongo_subtitle_bgcolor',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background color', 'hongo-addons'),
                'param_name' => 'hongo_box_background',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-3' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Input background color', 'hongo-addons'),
                'param_name' => 'hongo_box_bgcolor',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-2','hongo-content-newsletter-4' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Email placeholder color', 'hongo-addons'),
                'param_name' => 'hongo_box_text_color',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Email border color', 'hongo-addons'),
                'param_name' => 'hongo_box_border_color',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Button background color', 'hongo-addons'),
                'param_name' => 'hongo_button_bgcolor',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-4','hongo-content-newsletter-5' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Button hover background color', 'hongo-addons'),
                'param_name' => 'hongo_button_hover_bgcolor',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-4','hongo-content-newsletter-5' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Button / Icon text color', 'hongo-addons'),
                'param_name' => 'hongo_button_text_color',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Button / Icon text hover color', 'hongo-addons'),
                'param_name' => 'hongo_button_text_hover_color',
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ), 
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_title_setting',
                'heading'    => esc_html__( 'Title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Use additional font for title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_title',
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std'        => '1',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-left-setting typography-full-setting',
                'description'=> esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_subtitle_setting',
                'heading'    => esc_html__( 'Subtitle typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Use additional font for subtitle', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_subtitle',
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std'        => '1',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-left-setting typography-full-setting',
                'description'=> esc_html__( 'If On is selected then subtitle will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_content_setting',
                'heading'    => esc_html__( 'Content typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Use additional font for content', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_content',
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std'        => '1',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-left-setting typography-full-setting',
                'description'=> esc_html__( 'If On is selected then content will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type' => 'css_editor',
                'heading' => esc_html__( 'CSS box', 'hongo-addons' ),
                'param_name' => 'css',
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_bg_image_type', 
                'heading' => esc_html__( 'Background type', 'hongo-addons' ),
                'value' => array(
                    esc_html__('Select background type', 'hongo-addons') => '',
                    esc_html__('Fix background', 'hongo-addons') => 'fix-background',
                    esc_html__('Cover background', 'hongo-addons') => 'cover-background',
                ),
                'edit_field_class' => 'vc_col-sm-3 vc_column-with-padding',
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6')),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Background position', 'hongo-addons' ),
                'param_name' => 'desktop_bg_image_position',
                'value' => $hongo_desktop_bg_image_position,
                'edit_field_class' => 'vc_col-sm-3',
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Width', 'hongo-addons' ),
                'param_name' => 'desktop_width',
                'value' => '',
                'edit_field_class' => 'vc_col-sm-3',
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'param_name' => 'hongo_custom_separator_heading',
                'type' => 'hongo_custom_title',
                'value' => '',
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )), 
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Enable responsive css box', 'hongo-addons'),
                'param_name' => 'hongo_enable_responsive_css',
                'value' => array(
                    esc_html__( 'OFF', 'hongo-addons') => '0',
                    esc_html__( 'ON', 'hongo-addons') => '1'
                ),
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_newsletter_style', 'value' => array( 'hongo-content-newsletter-1','hongo-content-newsletter-2','hongo-content-newsletter-3','hongo-content-newsletter-4','hongo-content-newsletter-5','hongo-content-newsletter-6' )),
            ),
            array(
                'type' => 'responsive_css_editor',
                'heading' => esc_html__( 'Responsive css box', 'hongo-addons' ),
                'param_name' => 'responsive_css',
                'height' => 'no',
                'dependency' => array( 'element' => 'hongo_enable_responsive_css', 'value' => array('1') ),
                'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        ),
    ) 
);