<?php
/**
 * Shortcode Map For Shop Slider
 *
 * @package Hongo
 */
?>
<?php 
/*-----------------------------------------------------------------------------------*/
/* Shop Slider */
/*-----------------------------------------------------------------------------------*/

vc_map(
    array(
        'icon' => 'hongo-shortcode-icon fa-solid fa-arrows-alt-h',
        'name' => esc_html__( 'Shop Slider', 'hongo-addons' ),
        'base' => 'hongo_shop_slider',
        'description' => esc_html__( 'Product image slider', 'hongo-addons' ),
        'category' => 'Hongo',
        'params' => array(
            array(
		        'type' => 'dropdown',
	            'heading' => esc_html__( 'Select style', 'hongo-addons' ),
	            'param_name' => 'hongo_slider_style',
	            'admin_label' => true,
	            'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons') => 'hongo-shop-slider-style-1',
	                esc_html__( 'Style 2', 'hongo-addons') => 'hongo-shop-slider-style-2',
	                esc_html__( 'Style 3', 'hongo-addons') => 'hongo-shop-slider-style-3',
                    esc_html__( 'Style 4', 'hongo-addons') => 'hongo-shop-slider-style-4',
                    esc_html__( 'Style 5', 'hongo-addons') => 'hongo-shop-slider-style-5',
                    esc_html__( 'Style 6', 'hongo-addons') => 'hongo-shop-slider-style-6',
                    esc_html__( 'Style 7', 'hongo-addons') => 'hongo-shop-slider-style-7',
                    esc_html__( 'Style 8', 'hongo-addons') => 'hongo-shop-slider-style-8',
	            ),
    	    ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__( 'Select pre-made style for shop slider', 'hongo-addons' ),
                'param_name' => 'hongo_slider_preview_images',                
            ), 
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'heading' => esc_html__( 'Full screen', 'hongo-addons' ),
                'param_name' => 'hongo_full_screen',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select ON to show full screen slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5', 'hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Custom height in desktop', 'hongo-addons' ),
                'param_name' => 'custom_height',
                'std' => '760px',
                'description' => esc_html__( 'Enter custom height in desktop Ex: 760px', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_full_screen', 'value' => array('0') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Custom height in mini desktop', 'hongo-addons' ),
                'param_name' => 'custom_height_mini_desktop',
                'description' => esc_html__( 'Enter custom height in mini desktop Ex: 760px', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5', 'hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Custom height in tablet', 'hongo-addons' ),
                'param_name' => 'custom_height_tablet',
                'description' => esc_html__( 'Enter custom height in tablet Ex: 760px', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5', 'hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',                
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Custom height in mobile', 'hongo-addons' ),
                'param_name' => 'custom_height_mobile',
                'value' => '',
                'description' => esc_html__( 'Enter custom height in mobile Ex: 760px', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5', 'hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Social', 'hongo-addons' ),
                'param_name' => 'hongo_enable_social',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-6' ) ),
            ),
            array(
                'type' => 'param_group', // this param type
                'param_name' => 'hongo_shop_slider_slide', // all params must have a unique name
                'heading' => esc_html__( 'Slide', 'hongo-addons' ),
                'value' => '',
                'group' => esc_html__( 'Slides', 'hongo-addons' ),                
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value'   => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ),),
                'params' => array(
                    array(
			            'type' => 'attach_image',
			            'heading' => esc_html__( 'Image', 'hongo-addons' ),
			            'param_name' => 'hongo_image',
                        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
			        ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                        'param_name' => 'hongo_image_srcset',
                        'value' => hongo_get_thumbnail_image_sizes(),
                        'std' => 'full',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'attach_image',
                        'heading' => esc_html__( 'Brand image', 'hongo-addons' ),
                        'param_name' => 'hongo_brand_image',
                        'description' => esc_html__( 'Use only for style 7', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6 vc_el-clearfix',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Brand image thumbnail size', 'hongo-addons' ),
                        'param_name' => 'hongo_brand_image_srcset',
                        'value' => hongo_get_thumbnail_image_sizes(),
                        'std' => 'full',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Title', 'hongo-addons' ),
                        'param_name' => 'hongo_title',
                        'admin_label' => true,
                        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6 vc_el-clearfix',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Subtitle', 'hongo-addons' ),
                        'param_name' => 'hongo_subtitle',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textarea',
                        'heading' => esc_html__( 'Content', 'hongo-addons' ),
                        'param_name' => 'hongo_content',
                        'edit_field_class' => 'vc_col-sm-12',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Regular price', 'hongo-addons' ),
                        'param_name' => 'hongo_regular_price',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Sale price', 'hongo-addons' ),
                        'param_name' => 'hongo_sale_price',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Bottom title', 'hongo-addons' ),
                        'param_name' => 'hongo_bottom_title',
                        'description' => esc_html__( 'Use only for style 6', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'vc_link',
                        'class'       => '',
                        'heading'     => esc_html__( 'Button configuration', 'hongo-addons' ),
                        'param_name'  => 'shop_button',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'hongo_custom_switch_option',
                        'heading' => esc_html__( 'Button icon', 'hongo-addons' ),
                        'param_name' => 'hongo_enable_icon',
                        'value' => array(
                            esc_html__( 'Off', 'hongo-addons') => '0', 
                            esc_html__( 'On', 'hongo-addons') => '1'
                        ),
                        'std' => '0',
                        'edit_field_class' => 'vc_col-sm-6 vc_el-clearfix',
                    ),
                    array(
                        'type' => 'hongo_custom_switch_option',
                        'heading' => esc_html__('Custom icon image', 'hongo-addons'),
                        'param_name' => 'custom_icon',
                        'value' => array(
                            esc_html__('Off', 'hongo-addons') => '0',
                            esc_html__('On', 'hongo-addons') => '1'
                        ),
                        'dependency'  => array( 'element' => 'hongo_enable_icon', 'value' => '1' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'attach_image',
                        'heading' => esc_html__('Custom image', 'hongo-addons'),
                        'param_name' => 'custom_icon_image',
                        'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
                        'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Icon image maximum width', 'hongo-addons' ),
                        'param_name' => 'custom_icon_max_width',
                        'value' => '',
                        'dependency'  => array( 'element' => 'custom_icon', 'value' => array( '1' ) ),
                        'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__('Icon size', 'hongo-addons'),
                        'param_name' => 'hongo_icon_type',
                        'value' => array(
                            esc_html__('Select', 'hongo-addons') => '',
                            esc_html__('Extra large', 'hongo-addons') => 'icon-extra-large',
                            esc_html__('Large', 'hongo-addons') => 'icon-large',
                            esc_html__('Extra medium', 'hongo-addons') => 'icon-extra-medium',
                            esc_html__('Medium', 'hongo-addons') => 'icon-medium',
                            esc_html__('Extra small', 'hongo-addons') => 'icon-extra-small',
                            esc_html__('Small', 'hongo-addons') => 'icon-small',
                            esc_html__('Very small', 'hongo-addons') => 'icon-very-small',
                        ),
                       'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__('Icon position', 'hongo-addons'),
                        'param_name' => 'hongo_icon_position',
                        'value' => array(
                            esc_html__('Select', 'hongo-addons') => '',
                            esc_html__('Left', 'hongo-addons') => 'left',
                            esc_html__('Right', 'hongo-addons') => 'right',
                        ),                        
                        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'hongo_icon',
                        'heading' => esc_html__('Font icon', 'hongo-addons'),
                        'param_name' => 'hongo_button_icon',
                        'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                        'edit_field_class' => 'vc_col-sm-12',
                    ),
                    array(
                        'type'       => 'colorpicker',
                        'class'      => '',
                        'heading'    => esc_html__( 'Box background color', 'hongo-addons' ),
                        'param_name' => 'hongo_background_color',
                        'description' => esc_html__( 'Use only for style 1,5,8', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
			        array(
	                    'type' => 'dropdown',
	                    'heading' => esc_html__( 'Content position', 'hongo-addons' ),
	                    'param_name' => 'slider_content_position',
	       	            'value' => array(
                            esc_html__( 'Select', 'hongo-addons' ) => '', 
                            esc_html__( 'Left', 'hongo-addons' ) => 'left-content',
                            esc_html__( 'Center', 'hongo-addons' ) => 'center-content',
	       				    esc_html__( 'Right', 'hongo-addons') => 'right-content',
                        ),
                       'edit_field_class' => 'vc_col-sm-6',
	                ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Content alignment', 'hongo-addons' ),
                        'param_name' => 'slider_content_alignment',
                        'value' => array(
                            esc_html__( 'Select', 'hongo-addons' ) => '', 
                            esc_html__( 'Left', 'hongo-addons' ) => 'text-left',
                            esc_html__( 'Center', 'hongo-addons' ) => 'text-center',
                            esc_html__( 'Right', 'hongo-addons') => 'text-right',
                        ),
                       'edit_field_class' => 'vc_col-sm-6',
                    ),
		        ),
                'callbacks' => array(
                  'after_add' => 'vcChartParamAfterAddCallback',
                ),
		    ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slide direction', 'hongo-addons' ),
                'param_name' => 'slide_direction',
                'value' => array( 
                    esc_html__( 'Horizontal', 'hongo-addons' ) => 'horizontal',
                    esc_html__( 'Vertical', 'hongo-addons' ) => 'vertical',
                ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Mousewheel control', 'hongo-addons'),
                'param_name' => 'mousewheel_control',
                'value' => array(
                               esc_html__( 'Off', 'hongo-addons') => '0',
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'std'  => '1',
                'dependency' => array( 'element' => 'slide_direction', 'value' => array('vertical') ),
                'description' => esc_html__( 'Notice: If select slide direction vertical then mousewheel control works fine.', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Transition style', 'hongo-addons' ),
                'param_name' => 'hongo_transition_style',                
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Slide style', 'hongo-addons') => 'slide',
                    esc_html__( 'Fade style', 'hongo-addons') => 'fade',
                    esc_html__( 'Cube style', 'hongo-addons') => 'cube',
                    esc_html__( 'Coverflow style', 'hongo-addons') => 'coverflow',
                    esc_html__( 'Flip style', 'hongo-addons') => 'flip'
                ),
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'heading' => esc_html__( 'Pagination', 'hongo-addons' ),
                'param_name' => 'hongo_show_pagination',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select ON to show pagination in slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Pagination style', 'hongo-addons' ),
                'param_name' => 'show_pagination_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Dot style', 'hongo-addons') => 'swiper-pagination-dots',
                    esc_html__( 'Line style', 'hongo-addons') => 'swiper-pagination-square',
                    esc_html__( 'Dot border style', 'hongo-addons') => 'swiper-pagination-border',
                    esc_html__( 'Number style', 'hongo-addons') => 'swiper-pagination-number',
                ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_active_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'heading' => esc_html__( 'Navigation', 'hongo-addons' ),
                'param_name' => 'hongo_show_navigation',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'std' => '1',
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal' ) ),
                'description' => esc_html__( 'Select ON to show navigation in slider ( Note: All navigation settings not work in style 4 )', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Navigation style', 'hongo-addons' ),
                'param_name' => 'show_navigation_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Next/Prev arrow', 'hongo-addons') => 'next-prev-arrow',
                    esc_html__( 'Number navigation', 'hongo-addons') => 'number-arrow'
                ),
                'dependency' => array( 'element' => 'hongo_show_navigation', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Navigation color', 'hongo-addons' ),
                'param_name' => 'hongo_navigation_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_navigation', 'value' => array('1') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Cursor color style', 'hongo-addons' ),
                'param_name' => 'show_cursor_color_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'White cursor', 'hongo-addons') => 'white-move',
                    esc_html__( 'Black cursor', 'hongo-addons') => 'black-move',
                    esc_html__( 'Default cursor', 'hongo-addons') => 'cursor-default',
                    ),
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Transition speed', 'hongo-addons' ),
                'param_name' => 'hongo_slidespeed',
                'admin_label' => true,
                'value' => '',
                'description' => esc_html__( 'Enter slide speed time like 500, where 1000 = 1 second', 'hongo-addons' ),
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Autoplay', 'hongo-addons' ),
                'param_name' => 'autoplay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select On to autoplay slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal', 'vertical' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Slide delay', 'hongo-addons' ),
                'param_name' => 'slidedelay',
                'description' => esc_html__( 'Enter delay time (before switching to other slide) like 500, where 1000 = 1 second', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Loop', 'hongo-addons' ),
                'param_name' => 'autoloop',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'description' => esc_html__( 'Select On to autoloop slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'slide_direction', 'value' => array( 'horizontal' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Touch move', 'hongo-addons' ),
                'param_name' => 'touchmove',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
                'description' => esc_html__( 'Select Off then the only way to switch the slide is use of navigation and pagination.', 'hongo-addons' ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type'        => 'hongo_custom_social_sorting',
                'heading'     => esc_html__( 'Social sorting', 'hongo-addons'),
                'param_name'  => 'hongo_social_sorting',
                'value'       => array(
                    esc_html__( 'Facebook', 'hongo-addons')      => 'facebook',
                    esc_html__( 'Twitter', 'hongo-addons')       => 'twitter',
                    esc_html__( 'Dribbble', 'hongo-addons')      => 'dribbble',
                    esc_html__( 'LinkedIn', 'hongo-addons')      => 'linkedin',
                    esc_html__( 'Instagram', 'hongo-addons')     => 'instagram',
                    esc_html__( 'Tumblr', 'hongo-addons')        => 'tumblr',
                    esc_html__( 'Pinterest', 'hongo-addons')     => 'pinterest',
                    esc_html__( 'Youtube', 'hongo-addons')       => 'youtube',
                    esc_html__( 'Vimeo', 'hongo-addons')         => 'vimeo',
                    esc_html__( 'Soundcloud', 'hongo-addons')    => 'soundcloud',
                    esc_html__( 'Flickr', 'hongo-addons')        => 'flickr',
                    esc_html__( 'RSS', 'hongo-addons')           => 'rss',
                    esc_html__( 'Reddit', 'hongo-addons')        => 'reddit',
                    esc_html__( 'Behance', 'hongo-addons')       => 'behance',
                    esc_html__( 'Vine', 'hongo-addons')          => 'vine',
                    esc_html__( 'GitHub', 'hongo-addons')        => 'github',
                    esc_html__( 'Xing', 'hongo-addons')          => 'xing',
                    esc_html__( 'VK', 'hongo-addons')            => 'vk',
                    esc_html__( 'Yelp', 'hongo-addons')          => 'yelp',
                    esc_html__( 'Discord', 'hongo-addons')       => 'discord',
                    esc_html__( 'Skype', 'hongo-addons')       => 'skype',
                    esc_html__( 'Email address', 'hongo-addons') => 'email',
                ),
                'std' => '',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Social text', 'hongo-addons' ),
                'param_name' => 'hongo_enable_text',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Text', 'hongo-addons' ),
                'param_name' => 'hongo_social_text',
                'value' => 'Follow Us',
                'dependency'  => array( 'element' => 'hongo_enable_text', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),                       
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Facebook URL', 'hongo-addons' ),
                'param_name' => 'hongo_fb_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Twitter URL', 'hongo-addons' ),
                'param_name' => 'hongo_tw_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),            
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Dribbble URL', 'hongo-addons' ),
                'param_name' => 'hongo_db_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Linkedin URL', 'hongo-addons' ),
                'param_name' => 'hongo_li_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Instagram URL', 'hongo-addons' ),
                'param_name' => 'hongo_ig_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Tumblr URL', 'hongo-addons' ),
                'param_name' => 'hongo_tb_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Pinterest URL', 'hongo-addons' ),
                'param_name' => 'hongo_pi_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'YouTube URL', 'hongo-addons' ),
                'param_name' => 'hongo_yt_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Vimeo URL', 'hongo-addons' ),
                'param_name' => 'hongo_vm_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Soundcloud URL', 'hongo-addons' ),
                'param_name' => 'hongo_sc_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Flickr URL', 'hongo-addons' ),
                'param_name' => 'hongo_fk_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'RSS URL', 'hongo-addons' ),
                'param_name' => 'hongo_rss_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Reddit URL', 'hongo-addons' ),
                'param_name' => 'hongo_rd_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Behance URL', 'hongo-addons' ),
                'param_name' => 'hongo_bh_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Vine URL', 'hongo-addons' ),
                'param_name' => 'hongo_vine_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'GitHub URL', 'hongo-addons' ),
                'param_name' => 'hongo_gh_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Xing URL', 'hongo-addons' ),
                'param_name' => 'hongo_xing_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'VK URL', 'hongo-addons' ),
                'param_name' => 'hongo_vk_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Yelp address', 'hongo-addons' ),
                'param_name' => 'hongo_yelp_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Discord address', 'hongo-addons' ),
                'param_name' => 'hongo_discord_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Skype address', 'hongo-addons' ),
                'param_name' => 'hongo_skype_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Email address', 'hongo-addons' ),
                'param_name' => 'hongo_email_url',
                'dependency'  => array( 'element' => 'hongo_enable_social', 'value' => array('1') ),
                'group'       => esc_html__( 'Social', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Overlay', 'hongo-addons' ),
                'param_name' => 'show_overlay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Overlay color', 'hongo-addons' ),
                'param_name' => 'hongo_row_overlay_color',
                'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Overlay opacity', 'hongo-addons' ),
                'param_name' => 'hongo_overlay_opacity',
                'admin_label' => true,
                'value' => array( esc_html__( 'No opacity','hongo-addons') => '',
                    '0.1'  => '0.1',
                    '0.2'  => '0.2',
                    '0.3'  => '0.3',
                    '0.4'  => '0.4',
                    '0.5'  => '0.5',
                    '0.6'  => '0.6',
                    '0.7'  => '0.7',
                    '0.8'  => '0.8',
                    '0.9'  => '0.9',
                    '1.0'  => '1.0',
                ),
                'std' => '0.7',
                'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Z-index', 'hongo-addons' ),
                'param_name' => 'hongo_z_index',
                'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),

            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Overlay', 'hongo-addons' ),
                'param_name' => 'custom_show_overlay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-5' ) ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),            
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Overlay opacity', 'hongo-addons' ),
                'param_name' => 'hongo_custom_overlay_opacity',
                'admin_label' => true,
                'value' => array( esc_html__( 'No opacity','hongo-addons') => '',
                    '0.1'  => '0.1',
                    '0.2'  => '0.2',
                    '0.3'  => '0.3',
                    '0.4'  => '0.4',
                    '0.5'  => '0.5',
                    '0.6'  => '0.6',
                    '0.7'  => '0.7',
                    '0.8'  => '0.8',
                    '0.9'  => '0.9',
                    '1.0'  => '1.0',
                ),
                'std' => '0.7',
                'dependency' => array( 'element' => 'custom_show_overlay', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Z-index', 'hongo-addons' ),
                'param_name' => 'hongo_custom_z_index',
                'dependency' => array( 'element' => 'custom_show_overlay', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_width',
                'heading' => esc_html__( 'Content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_mini_width',
                'heading' => esc_html__( 'Content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_ipad_width',
                'heading' => esc_html__( 'Content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_mobile_width',
                'heading' => esc_html__( 'Content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Black', 'hongo-addons') => 'style1',
                    esc_html__('White', 'hongo-addons') => 'style2',
                    esc_html__('Base color', 'hongo-addons') => 'style10',
                    esc_html__('Black border', 'hongo-addons') => 'style3',
                    esc_html__('White border', 'hongo-addons') => 'style4',
                    esc_html__('Base color border', 'hongo-addons') => 'style11',
                    esc_html__('Black round corner', 'hongo-addons') => 'style5',
                    esc_html__('White round corner', 'hongo-addons') => 'style6',
                    esc_html__('Base color round corner', 'hongo-addons') => 'style12',
                    esc_html__('Black border with rounded', 'hongo-addons') => 'style7',
                    esc_html__('White border with rounded', 'hongo-addons') => 'style8',
                    esc_html__('Base color border with rounded', 'hongo-addons') => 'style13',
                    esc_html__('Text with underline', 'hongo-addons') => 'style9',
                    esc_html__('Base color text with underline', 'hongo-addons') => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button size', 'hongo-addons'),
                'param_name' => 'hongo_button_type',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Extra Large', 'hongo-addons') => 'extra-large',
                    esc_html__('Large', 'hongo-addons') => 'large',
                    esc_html__('Medium', 'hongo-addons') => 'medium',
                    esc_html__('Small', 'hongo-addons') => 'small',
                    esc_html__('Very Small', 'hongo-addons') => 'vsmall',
                ),
                'edit_field_class' => 'vc_col-sm-6 button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type'        => 'hongo_button_settings',
                'param_name'  => 'hongo_button_setting',
                'heading'     => esc_html__( 'Button typography', 'hongo-addons' ),                
                'group' => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type'        => 'hongo_button_settings',
                'param_name'  => 'hongo_icon_button',
                'heading'     => esc_html__( 'Social icon typography', 'hongo-addons' ),
                'group' => esc_html__( 'Button Settings', 'hongo-addons' ),
                'hide_element_keys' =>array('text-color','text-hover-color','background-color','background-hover-color','border-color','border-hover-color', 'font-transform', 'text-decoration', 'border-radius', 'border-width', 'letter-spacing', 'font-weight'),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-6' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_title_setting',
                'heading'     => esc_html__( 'Title typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'title_heading_tag',                
                'value' => $hongo_element_tag,
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',                
                'heading' => esc_html__( 'Use additional font for title', 'hongo-addons' ),
                'param_name' => 'additional_font_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_subtitle_setting',
                'heading'     => esc_html__( 'Subtitle typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Subtitle element tag', 'hongo-addons'),
                'param_name' => 'subtitle_heading_tag',                
                'value' => $hongo_element_tag,
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',                
                'heading' => esc_html__( 'Use additional font for subtitle', 'hongo-addons' ),
                'param_name' => 'additional_font_subtitle',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then subtitle will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Border color', 'hongo-addons' ),
                'param_name' => 'hongo_border_color',
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-3') ),
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-full-setting',
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_content_setting',
                'heading'     => esc_html__( 'Content typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),       
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8') ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_regular_price_setting',
                'heading'     => esc_html__( 'Regular price typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_sale_price_setting',
                'heading'     => esc_html__( 'Sale price typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_slider_style', 'value' => array( 'hongo-shop-slider-style-1','hongo-shop-slider-style-2','hongo-shop-slider-style-3','hongo-shop-slider-style-4','hongo-shop-slider-style-5','hongo-shop-slider-style-6','hongo-shop-slider-style-7','hongo-shop-slider-style-8' ) ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_bottom_title_setting',
                'heading'     => esc_html__( 'Bottom title typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-6') ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_social_text_setting',
                'heading'     => esc_html__( 'Social text typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),
                'dependency'  => array( 'element' => 'hongo_slider_style', 'value' => array('hongo-shop-slider-style-6') ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Element ID', 'hongo-addons' ),
                'description' => sprintf( esc_html__( 'Enter element ID (Note: make sure it is unique and valid according to %s).', 'hongo-addons' ), '<a target="_blank" href="https://www.w3schools.com/tags/att_global_id.asp">w3c specification</a>'),
                'param_name'  => 'hongo_slider_id',
                'group'       => esc_html__( 'Extras', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Extra class name', 'hongo-addons' ),
                'description' => esc_html__( 'Add additional CSS class to this element, you can define multiple CSS class with use of space like "Class1 Class2". You can write css code using this class and add it in customizer or your child theme css file.', 'hongo-addons' ),
                'param_name'  => 'hongo_slider_class',
                'group'       => esc_html__( 'Extras', 'hongo-addons' ),
            ),
        ),
    )
);