<?php
/**
 * Shortcode Map For Text Slider
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Text Slider */
/*-----------------------------------------------------------------------------------*/

$hongo_text_slider_class = 'hongo-text-slider-'.time() .'-2-'.rand( 0, 100 );

vc_map( 
    array(
        'name' => esc_html__( 'Text Slider', 'hongo-addons' ),
        'base' => 'hongo_text_slider',
        'description' => esc_html__( 'Fancy text based slider', 'hongo-addons' ),
        'icon' => 'fa-solid fa-arrows-alt-h hongo-shortcode-icon',
        'category' => 'Hongo',
        'params' => array(
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons'),
                'param_name' => 'text_slider_style',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',                    
                    esc_html__( 'Style 1', 'hongo-addons') => 'hongo-text-slider2',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__( 'Select pre-made style', 'hongo-addons'),
                'param_name' => 'text_slider_style_preview_image',
            ),            
            array(
                'param_name' => 'hongo_text_slides',
                'type' => 'param_group',
                'heading' => esc_html__( 'Slide', 'hongo-addons' ),
                'value' => '',
                'params' => array(
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Title', 'hongo-addons' ),
                        'param_name' => 'hongo_title',
                        'admin_label' => true,
                        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Subtitle', 'hongo-addons' ),
                        'param_name' => 'hongo_subtitle',
                    ),
                    array(
                        'type' => 'textarea',
                        'heading' => esc_html__( 'Content', 'hongo-addons' ),
                        'param_name' => 'hongo_content',
                        'description' => esc_html__( 'Only for style-2', 'hongo-addons' ),
                    ),
                    array(
                        'type'        => 'vc_link',
                        'heading'     => esc_html__( 'Button configuration', 'hongo-addons' ),
                        'param_name'  => 'hongo_button_config',
                        'description' => esc_html__( 'Only for style-2', 'hongo-addons' ),
                    ),
                    array(
                        'type' => 'hongo_custom_switch_option',
                        'heading' => esc_html__('Button one page navigation', 'hongo-addons'),
                        'param_name' => 'hongo_button_one_page',
                        'value' => array(esc_html__('Off', 'hongo-addons') => '0',
                                         esc_html__('On', 'hongo-addons') => '1'
                                        ),
                    ),
                ),
                'callbacks' => array(
                    'after_add' => 'vcChartParamAfterAddCallback',
                ),
                'group' => esc_html__( 'Slides', 'hongo-addons'),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Navigation', 'hongo-addons'),
                'param_name' => 'hongo_show_navigation',
                'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
                'std' => '1',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'description' => esc_html__( 'Select ON to show navigation in slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Cursor color style', 'hongo-addons' ),
                'param_name' => 'hongo_show_cursor_color_style',
                'admin_label' => true,
                'value' => array(
                              esc_html__( 'Select', 'hongo-addons' ) => '',
                              esc_html__( 'White cursor', 'hongo-addons' ) => 'white-move',
                              esc_html__( 'Black cursor', 'hongo-addons' ) => 'black-move',
                              esc_html__( 'Default cursor', 'hongo-addons' ) => 'cursor-default',
                          ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Navigation color', 'hongo-addons' ),
                'param_name' => 'hongo_navigation_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_show_navigation', 'value' => array('1') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Transition speed', 'hongo-addons'),
                'param_name' => 'slidespeed',
                'admin_label' => true,
                'value' => '',
                'description' => esc_html__( 'Enter slide speed time like 500, where 1000 = 1 second', 'hongo-addons'),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Autoplay', 'hongo-addons'),
                'param_name' => 'autoplay',
                'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                                 esc_html__( 'On', 'hongo-addons') => '1'
                                ),
                'description' => esc_html__( 'Select On to autoplay slider', 'hongo-addons' ),
                'std' => '1',
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Slide delay', 'hongo-addons'),
                'param_name' => 'slidedelay',
                'admin_label' => true,
                'value' => '',
                'description' => esc_html__( 'Enter delay time (before switching to other slide) like 500, where 1000 = 1 second', 'hongo-addons'),
                'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Loop', 'hongo-addons'),
                'param_name' => 'autoloop',
                'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                                 esc_html__( 'On', 'hongo-addons') => '1'
                                ),
                'description' => esc_html__( 'Select On to autoloop slider', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_width',
                'heading' => esc_html__( 'Content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_mini_width',
                'heading' => esc_html__( 'Content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_ipad_width',
                'heading' => esc_html__( 'Content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_mobile_width',
                'heading' => esc_html__( 'Content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Black', 'hongo-addons') => 'style1',
                    esc_html__('White', 'hongo-addons') => 'style2',
                    esc_html__('Base color', 'hongo-addons') => 'style10',
                    esc_html__('Black border', 'hongo-addons') => 'style3',
                    esc_html__('White border', 'hongo-addons') => 'style4',
                    esc_html__('Base color border', 'hongo-addons') => 'style11',
                    esc_html__('Black round corner', 'hongo-addons') => 'style5',
                    esc_html__('White round corner', 'hongo-addons') => 'style6',
                    esc_html__('Base color round corner', 'hongo-addons') => 'style12',
                    esc_html__('Black border with rounded', 'hongo-addons') => 'style7',
                    esc_html__('White border with rounded', 'hongo-addons') => 'style8',
                    esc_html__('Base color border with rounded', 'hongo-addons') => 'style13',
                    esc_html__('Text with underline', 'hongo-addons') => 'style9',
                    esc_html__('Base color text with underline', 'hongo-addons') => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button size', 'hongo-addons'),
                'param_name' => 'hongo_button_type',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Extra Large', 'hongo-addons') => 'extra-large',
                    esc_html__('Large', 'hongo-addons') => 'large',
                    esc_html__('Medium', 'hongo-addons') => 'medium',
                    esc_html__('Small', 'hongo-addons') => 'small',
                    esc_html__('Very Small', 'hongo-addons') => 'vsmall',
                ),
                'edit_field_class' => 'vc_col-sm-6 button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
            ),
            array(
                'type'       => 'hongo_button_settings',
                'param_name' => 'hongo_button_setting',
                'heading'    => esc_html__( 'Button typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'hide_element_keys' => array( 'icon-color','icon-hover-color'),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_number_setting',
                'heading'    => esc_html__( 'Number typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array('hongo-text-slider2') ),
                'hide_element_keys' => array( 'text-hover-color','font-transform', 'text-align' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_title_setting',
                'heading'    => esc_html__( 'Title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'hongo_title_element_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_title',
                'value' => array(
                  esc_html__( 'Off', 'hongo-addons') => '0', 
                  esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_subtitle_setting',
                'heading'    => esc_html__( 'Subtitle typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
                ),
                array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Subtitle element tag', 'hongo-addons'),
                'param_name' => 'hongo_subtitle_element_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for sub-title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_subtitle',
                'value' => array(
                  esc_html__( 'Off', 'hongo-addons') => '0', 
                  esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_content_setting',
                'heading'    => esc_html__( 'Content typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'text_slider_style', 'value' => array( 'hongo-text-slider2' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Element ID', 'hongo-addons' ),
                'description' => sprintf( esc_html__( 'Enter element ID (Note: make sure it is unique and valid according to %s).', 'hongo-addons'), '<a target="_blank" href="https://www.w3schools.com/tags/att_global_id.asp">w3c specification</a>'),
                'param_name'  => 'hongo_slider_id',
                'group'       => esc_html__( 'Extras', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Extra class name', 'hongo-addons' ),
                'description' => esc_html__( 'Add additional CSS class to this element, you can define multiple CSS class with use of space like "Class1 Class2". You can write css code using this class and add it in customizer or your child theme css file.', 'hongo-addons' ),
                'param_name'  => 'hongo_slider_class',
                'group'       => esc_html__( 'Extras', 'hongo-addons' ),
            ),
          ),
      )
  );