<?php
/**
 * Shortcode Map For Price Table
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Price Table */
/*-----------------------------------------------------------------------------------*/

vc_map( 
    array(
        'name' => esc_html__( 'Price Table', 'hongo-addons' ),
        'base' => 'hongo_pricing_table',
        'description' => esc_html__( 'Display pricing tables', 'hongo-addons' ),
        'icon' => 'fa-solid fa-table hongo-shortcode-icon',
        'category' => 'Hongo',
        'params' => array(
            array(
                'type' => 'hongo_preview_image',
                'param_name' => 'hongo_price_table_preview_image',
                'image_src' => HONGO_SHORTCODE_ADDONS_PREVIEW_IMAGE.'/price-table.jpg',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Custom icon image', 'hongo-addons'),
                'param_name' => 'custom_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
            ),
            array(
                'type' => 'attach_image',
                'heading' => esc_html__( 'Custom image', 'hongo-addons'),
                'param_name' => 'custom_icon_image',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
                'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Extra Medium - 40px X 40px, Medium - 35px X 35px, Small - 24px X 24px, Extra Small - 16px X 16px', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Icon image maximum width', 'hongo-addons' ),
                'param_name' => 'custom_icon_max_width',
                'value' => '',
                'dependency'  => array( 'element' => 'custom_icon', 'value' => array( '1' ) ),
                'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__( 'Font icon', 'hongo-addons'),
                'param_name' => 'pricing_table_icon',
                'admin_label' => true,
                'value' => '',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Title', 'hongo-addons'),
                'param_name' => 'sale_type',
                'admin_label' => true,
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Price', 'hongo-addons'),
                'param_name' => 'price',
                'admin_label' => true,
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Duration', 'hongo-addons'),
                'param_name' => 'per_price',
                'admin_label' => true,
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type' => 'textarea_html',
                'heading' => esc_html__( 'Features content', 'hongo-addons'),
                'param_name' => 'content',
                'std' => '<ul><li>1 GB photos</li><li>Secure online transfer</li><li>Unlimited styles</li><li>Customer service</li></ul>'
            ),
            array(
                'type'        => 'vc_link',
                'heading'     => esc_html__('Button configuration', 'hongo-addons' ),
                'param_name'  => 'hongo_button_config',
                'admin_label' => true,
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'class' => '',
                'heading' => esc_html__( 'Button Icon / Image', 'hongo-addons'),
                'param_name' => 'hongo_button_enable_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '0',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__('Button custom icon image', 'hongo-addons'),
                'param_name' => 'hongo_button_custom_icon',
                'value' => array(
                    esc_html__('Off', 'hongo-addons') => '0',
                    esc_html__('On', 'hongo-addons') => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_button_enable_icon', 'value' => '1' ),
            ),
            array(
                'type' => 'attach_image',
                'heading' => esc_html__( 'Button custom image', 'hongo-addons' ),
                'param_name' => 'hongo_button_custom_icon_image',
                'dependency' => array( 'element' => 'hongo_button_custom_icon', 'value' => '1' ),
                'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Button icon image maximum width', 'hongo-addons' ),
                'param_name' => 'hongo_button_custom_icon_max_width',
                'value' => '',
                'dependency'  => array( 'element' => 'hongo_button_custom_icon', 'value' => array( '1' ) ),
                'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button icon size', 'hongo-addons'),
                'param_name' => 'hongo_button_icon_type',
                'value' => array(
                    esc_html__('Select Icon Size', 'hongo-addons') => '',
                    esc_html__('Extra Large', 'hongo-addons') => 'icon-extra-large',
                    esc_html__('Large', 'hongo-addons') => 'icon-large',
                    esc_html__('Extra Medium', 'hongo-addons') => 'icon-extra-medium',
                    esc_html__('Medium', 'hongo-addons') => 'icon-medium',
                    esc_html__('Extra Small', 'hongo-addons') => 'icon-extra-small',
                    esc_html__('Small', 'hongo-addons') => 'icon-small',
                    esc_html__('Very Small', 'hongo-addons') => 'icon-very-small',
                ),
                'dependency' => array( 'element' => 'hongo_button_custom_icon', 'value' => '0' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button icon position', 'hongo-addons'),
                'param_name' => 'hongo_button_icon_position',
                'value' => array(
                    esc_html__('Left', 'hongo-addons') => 'left',
                    esc_html__('Right', 'hongo-addons') => 'right',
                ),
                'std' => 'left',
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => array( '1' ) ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__('Button font icon', 'hongo-addons'),
                'param_name' => 'hongo_button_icon',
                'admin_label' => true,
                'dependency' => array( 'element' => 'hongo_button_custom_icon', 'value' => '0' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_background_color',
                'value' => '',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Title background color', 'hongo-addons' ),
                'param_name' => 'hongo_title_background_color',
                'value' => '',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Features content border color', 'hongo-addons' ),
                'param_name' => 'hongo_features_border_color',
                'value' => '',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Icon size', 'hongo-addons'),
                'param_name' => 'hongo_pricing_table_icon_size',
                'admin_label' => true,
                'value' => array( esc_html__( 'Default','hongo-addons') => '',
                                  esc_html__( 'Extra large','hongo-addons') => 'icon-extra-large', 
                                  esc_html__( 'Large','hongo-addons') => 'icon-large',
                                  esc_html__( 'Extra medium','hongo-addons') => 'icon-extra-medium',
                                  esc_html__( 'Medium','hongo-addons') => 'icon-medium',
                                  esc_html__( 'Small','hongo-addons') => 'icon-small',
                                  esc_html__( 'Extra small','hongo-addons') => 'icon-extra-small',
                                ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'custom_icon', 'value' => array( '0' ) ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_color',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Black', 'hongo-addons') => 'style1',
                    esc_html__('White', 'hongo-addons') => 'style2',
                    esc_html__('Base color', 'hongo-addons') => 'style10',
                    esc_html__('Black border', 'hongo-addons') => 'style3',
                    esc_html__('White border', 'hongo-addons') => 'style4',
                    esc_html__('Base color border', 'hongo-addons') => 'style11',
                    esc_html__('Black round corner', 'hongo-addons') => 'style5',
                    esc_html__('White round corner', 'hongo-addons') => 'style6',
                    esc_html__('Base color round corner', 'hongo-addons') => 'style12',
                    esc_html__('Black border with rounded', 'hongo-addons') => 'style7',
                    esc_html__('White border with rounded', 'hongo-addons') => 'style8',
                    esc_html__('Base color border with rounded', 'hongo-addons') => 'style13',
                    esc_html__('Text with underline', 'hongo-addons') => 'style9',
                    esc_html__('Base color text with underline', 'hongo-addons') => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button size', 'hongo-addons'),
                'param_name' => 'hongo_button_type',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Extra Large', 'hongo-addons') => 'extra-large',
                    esc_html__('Large', 'hongo-addons') => 'large',
                    esc_html__('Medium', 'hongo-addons') => 'medium',
                    esc_html__('Small', 'hongo-addons') => 'small',
                    esc_html__('Very Small', 'hongo-addons') => 'vsmall',
                ),
                'edit_field_class' => 'vc_col-sm-6 button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
            ),
            array(
                'type'       => 'hongo_button_settings',
                'param_name' => 'hongo_button_setting',
                'heading'    => esc_html__( 'Button typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_title_setting',
                'heading'     => esc_html__( 'Title typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_price_setting',
                'heading'     => esc_html__( 'Price typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color','font-transform' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_duraction_setting',
                'heading'     => esc_html__( 'Duration typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_content_setting',
                'heading'     => esc_html__( 'Content typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        ),
    )
);