<?php
/**
 * Shortcode Map For Team Member
 *
 * @package Hongo
 */
?>
<?php

/*-----------------------------------------------------------------------------------*/
/* Team Member */
/*-----------------------------------------------------------------------------------*/

vc_map(
    array(
        'name' => esc_html__( 'Team Member', 'hongo-addons' ),
        'base' => 'hongo_team_member',
        'category' => 'Hongo',
        'icon' => 'fa-solid fa-user hongo-shortcode-icon',
        'description' => esc_html__( 'Organize team member profiles', 'hongo-addons' ),
        'params' => array(
            array(
                'type'        => 'dropdown',
                'heading'     => esc_html__( 'Style', 'hongo-addons'),
                'param_name'  => 'hongo_team_member_style',
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons') => 'team-style-1',
                    esc_html__( 'Style 2', 'hongo-addons') => 'team-style-2',
                    esc_html__( 'Style 3', 'hongo-addons') => 'team-style-3',
                ),
            ),
            array(
                'type'        => 'hongo_preview_image',
                'heading'     => esc_html__( 'Select pre-made style for block', 'hongo-addons'),
                'param_name'  => 'hongo_team_preview_image',
            ),
            array(
                'type'        => 'attach_image',
                'heading'     => esc_html__( 'Image', 'hongo-addons' ),
                'param_name'  => 'hongo_team_member_image',
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
            ),
            array(
                'type'        => 'dropdown',
                'heading'     => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                'param_name'  => 'hongo_image_srcset',
                'value'       => hongo_get_thumbnail_image_sizes(),
                'std' => 'full',
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Name', 'hongo-addons' ),
                'param_name'  => 'hongo_member_name',
                'admin_label' => true,
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Designation', 'hongo-addons' ),
                'param_name'  => 'hongo_member_des',
                'admin_label' => true,
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
	        array(
	            'type'        => 'hongo_custom_switch_option',
	            'heading'     => esc_html__( 'Separator', 'hongo-addons'),
	            'param_name'  => 'hongo_enable_separator',
	            'value' => array(
	                esc_html__( 'Off', 'hongo-addons') => '0', 
	                esc_html__( 'On', 'hongo-addons') => '1'
	            ),
	            'std' => '1',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-3') ),
	        ),
	        array(
	            'type' => 'hongo_custom_switch_option',
	            'heading' => esc_html__( 'Link on name', 'hongo-addons'),
	            'param_name' => 'hongo_enable_link',
	            'value' => array(
	                esc_html__( 'Off', 'hongo-addons') => '0', 
	                esc_html__( 'On', 'hongo-addons') => '1'
	            ),
	            'std' => '0',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	        ),
	        array(
	            'type' => 'dropdown',
	            'heading' => esc_html__( 'Link target', 'hongo-addons'),
	            'param_name' => 'hongo_link_target',
	            'value' => array(
	                esc_html__('Self', 'hongo-addons') => '_self', 
	                esc_html__('New tab / window', 'hongo-addons') => '_blank',
	                esc_html__('One page', 'hongo-addons') => 'one_page',
	            ),
	            'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
	        ),
	        array(
	            'type' => 'textfield',
	            'heading' =>esc_html__( 'Link / URL', 'hongo-addons'),
	            'param_name' => 'hongo_link_url',
	            'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
	            'description' => esc_html__( 'Enter full URL with http, like http://www.example.com', 'hongo-addons' ),
	        ),
	        array(
	            'type' => 'colorpicker',
	            'class' => '',
	            'heading' => esc_html__( 'Link hover color', 'hongo-addons' ),
	            'param_name' => 'hongo_link_hover_color',
	            'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
	        ),
	        array(
	            'type'        => 'hongo_custom_social_sorting',
	            'heading'     => esc_html__( 'Social sorting', 'hongo-addons'),
	            'param_name'  => 'hongo_social_sorting',
	            'value'       => array(
	                esc_html__( 'Facebook', 'hongo-addons')      => 'facebook',
	                esc_html__( 'Twitter', 'hongo-addons')       => 'twitter',
	                esc_html__( 'Dribbble', 'hongo-addons')      => 'dribbble',
	                esc_html__( 'LinkedIn', 'hongo-addons')      => 'linkedin',
	                esc_html__( 'Instagram', 'hongo-addons')     => 'instagram',
	                esc_html__( 'Tumblr', 'hongo-addons')        => 'tumblr',
	                esc_html__( 'Pinterest', 'hongo-addons')     => 'pinterest',
	                esc_html__( 'Youtube', 'hongo-addons')       => 'youtube',
	                esc_html__( 'Vimeo', 'hongo-addons')         => 'vimeo',
	                esc_html__( 'Soundcloud', 'hongo-addons')    => 'soundcloud',
	                esc_html__( 'Flickr', 'hongo-addons')        => 'flickr',
	                esc_html__( 'RSS', 'hongo-addons')           => 'rss',
	                esc_html__( 'Reddit', 'hongo-addons')        => 'reddit',
	                esc_html__( 'Behance', 'hongo-addons')       => 'behance',
	                esc_html__( 'Vine', 'hongo-addons')          => 'vine',
	                esc_html__( 'GitHub', 'hongo-addons')        => 'github',
	                esc_html__( 'Xing', 'hongo-addons')          => 'xing',
	                esc_html__( 'VK', 'hongo-addons')            => 'vk',
	                esc_html__( 'Yelp', 'hongo-addons')          => 'yelp',
	                esc_html__( 'Discord', 'hongo-addons')       => 'discord',
	                esc_html__( 'Skype', 'hongo-addons')       => 'skype',
	                esc_html__( 'Email address', 'hongo-addons') => 'email',
	            ),
	            'std' => '',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Facebook URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_facebook_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Twitter URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_twitter_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),	        
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Dribbble URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_db_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'LinkedIn URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_linkedin_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Instagram URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_instagram_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Tumblr URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_tb_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Pinterest URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_pinterest_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Youtube URL', 'hongo-addons'),
	            'param_name'  => 'hongo_yt_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Vimeo URL', 'hongo-addons'),
	            'param_name'  => 'hongo_vm_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Soundcloud URL', 'hongo-addons'),
	            'param_name'  => 'hongo_sc_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Flickr URL', 'hongo-addons'),
	            'param_name'  => 'hongo_fk_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('RSS URL', 'hongo-addons'),
	            'param_name'  => 'hongo_rss_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Reddit URL', 'hongo-addons'),
	            'param_name'  => 'hongo_rd_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__( 'Behance URL', 'hongo-addons' ),
	            'param_name'  => 'hongo_behance_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Vine URL', 'hongo-addons'),
	            'param_name'  => 'hongo_vine_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('GitHub URL', 'hongo-addons'),
	            'param_name'  => 'hongo_gh_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Xing URL', 'hongo-addons'),
	            'param_name'  => 'hongo_xing_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('VK URL', 'hongo-addons'),
	            'param_name'  => 'hongo_vk_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Yelp URL', 'hongo-addons'),
	            'param_name'  => 'hongo_yelp_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Discord URL', 'hongo-addons'),
	            'param_name'  => 'hongo_discord_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Skype URL', 'hongo-addons'),
	            'param_name'  => 'hongo_skype_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textfield',
	            'heading'     => esc_html__('Email address', 'hongo-addons'),
	            'param_name'  => 'hongo_email_url',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'textarea_raw_html',
	            'heading'     => esc_html__( 'Custom icons code', 'hongo-addons' ),
	            'value'      => base64_encode( 'CustomHTML' ),
	            'param_name'  => 'hongo_custom_link',
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	            'group'       => esc_html__( 'Social', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Box background caption color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_box_caption_bg_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-2') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Box gradient background color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_box_gradient_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Box hover background color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_box_hover_bg_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Box hover background gradient color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_box_hover_gradient_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'dropdown',
	          	'heading'     => esc_html__( 'Icon size', 'hongo-addons'),
	          	'param_name'  => 'hongo_icon_size',
	          	'value' => array(
	          		esc_html__( 'Default', 'hongo-addons') => '',
	                esc_html__( 'Extra large', 'hongo-addons') => 'icon-extra-large', 
	                esc_html__( 'Large', 'hongo-addons') => 'icon-large',
	                esc_html__( 'Extra medium', 'hongo-addons') => 'icon-extra-medium',
	                esc_html__( 'Medium', 'hongo-addons') => 'icon-medium',
	                esc_html__( 'Small', 'hongo-addons') => 'icon-small',
	                esc_html__( 'Extra small', 'hongo-addons') => 'icon-extra-small',
	            ),
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Icon color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_icon_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Icon hover color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_icon_hover_color',
	          	'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'textfield',
	          	'heading'     => esc_html__( 'Separator thickness', 'hongo-addons' ),
	          	'param_name'  => 'hongo_separator_height',
	          	'value'       => '2px',
	          	'description' => esc_html__( 'In pixel like 2px', 'hongo-addons' ),
	          	'dependency'  => array( 'element' => 'hongo_enable_separator', 'value' => array('1') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	          	'type'        => 'colorpicker',
	          	'class'       => '',
	          	'heading'     => esc_html__( 'Separator color', 'hongo-addons' ),
	          	'param_name'  => 'hongo_separator_color',
	          	'dependency'  => array( 'element' => 'hongo_enable_separator', 'value' => array('1') ),
	          	'group'       => esc_html__( 'Style', 'hongo-addons'),
	        ),
	        array(
	            'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_name_setting',
                'heading'     => esc_html__( 'Name typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
                'hide_element_keys' => array( 'text-hover-color' ),
	        ),
	        array(
                'type'        => 'dropdown',
                'heading'     => esc_html__( 'Name element tag', 'hongo-addons'),
                'param_name'  => 'hongo_member_name_element_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
            ),
            array(
		        'type' => 'hongo_custom_switch_option',
		        'heading' => esc_html__( 'Use additional font for name', 'hongo-addons'),
		        'param_name' => 'hongo_enable_name_alt_font',
		        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
		        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
		                         esc_html__( 'On', 'hongo-addons') => '1'
		                        ),
		        'std' => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
		        'group' => esc_html__( 'Typography', 'hongo-addons' ),
		        'description' => esc_html__( 'If On is selected then name will use additional font family setup in WordPress customizer', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
		    ),
	        array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_designation_setting',
                'heading'     => esc_html__( 'Designation typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	        ),
            array(
	            'type'        => 'dropdown',
	            'heading'     => esc_html__( 'Designation element tag', 'hongo-addons'),
	            'param_name'  => 'hongo_member_des_element_tag',
	            'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
	            'group' => esc_html__( 'Typography', 'hongo-addons' ), 
	            'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
	        ),
	        array(
		        'type' => 'hongo_custom_switch_option',
		        'heading' => esc_html__( 'Use additional font for designation', 'hongo-addons'),
		        'param_name' => 'hongo_enable_designation_alt_font',
		        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
		        'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
		                         esc_html__( 'On', 'hongo-addons') => '1'
		                        ),
		        'std' => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then designation will use additional font family setup in WordPress customizer', 'hongo-addons' ),
		        'group' => esc_html__( 'Typography', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_team_member_style', 'value' => array('team-style-1', 'team-style-2','team-style-3') ),
		    ),
	        $hongo_vc_extra_id,
	        $hongo_vc_extra_class,
      	)
    )
);