<?php
/**
 * Map For Image Carousel
 *
 * @package Hongo
 */
?>
<?php 
/*-----------------------------------------------------------------------------------*/
/* Image Carousel */
/*-----------------------------------------------------------------------------------*/

vc_map( 
    array(
        'name' => esc_html__('Image Carousel', 'hongo-addons'),
        'description' => esc_html__( 'Animated carousel with images', 'hongo-addons' ),
        'icon' => 'hongo-shortcode-icon fa-solid fa-images',
        'base' => 'hongo_image_carousel',
        'category' => 'Hongo',        
        'params' => array(
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons' ),
                'param_name' => 'image_gallery_type',
                'admin_label' => true,
                'value' => array(
                    esc_html__('Select', 'hongo-addons') => '',
                    esc_html__('Style 1', 'hongo-addons') => 'image-carousel-style-1',
                    esc_html__('Style 2', 'hongo-addons') => 'image-carousel-style-2',
                    esc_html__('Style 3', 'hongo-addons') => 'image-carousel-style-3',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__('Select pre-made style', 'hongo-addons'),
                'param_name' => 'hongo_image_gallery_preview_image',
            ),
            array(
                'type' => 'attach_images',
                'heading' => esc_html__('Images', 'hongo-addons'),
                'param_name' => 'image_gallery',
                'holder' => 'div',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2' )),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                'param_name' => 'hongo_image_srcset',
                'value' => hongo_get_thumbnail_image_sizes(),
                'std' => 'full',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2' )),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__('Lightbox gallery', 'hongo-addons'),
                'param_name' => 'lightbox_gallery',
                'value' => array(
                    esc_html__('Off', 'hongo-addons') => '0', 
                    esc_html__('On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1' ) ),
            ), 
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Zoom text', 'hongo-addons'),
                'param_name' => 'zoom_text',
                'std' => esc_html__( 'ENLARGE', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'lightbox_gallery', 'value' => array( '1' ) ),
            ),           
            array(
                'type' => 'animation_style',
                'heading' => esc_html__( 'Animation', 'hongo-addons' ),
                'param_name' => 'hongo_column_animation_style',
                'value' => '',
                'settings' => array(
                    'type' => array(
                        'in',
                        'other',
                    ),
                ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1' )),
                'description' => __( 'Select type of animation for element to be animated when it "enters" the browsers viewport (Note: works only in modern browsers).', 'hongo-addons' ),
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Animation duration', 'hongo-addons' ),
              'param_name' => 'hongo_animation_duration',
              'dependency' => array( 'element' => 'hongo_column_animation_style', 'value_not_equal_to' => array( 'none' ) ),
              'description' => esc_html__( 'Add animation duration in mls, like 200', 'hongo-addons' ),              
            ),
            array(
                'param_name' => 'hongo_image_slides',
                'type' => 'param_group',
                'heading' => esc_html__( 'Slide', 'hongo-addons' ),
                'value' => '',
                'params' => array(
                    array(
                        'type' => 'attach_image',
                        'heading' => esc_html__( 'Image', 'hongo-addons' ),
                        'param_name' => 'hongo_image',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Title', 'hongo-addons' ),
                        'param_name' => 'hongo_title',
                        'admin_label' => true,
                        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                        'param_name' => 'hongo_image_srcset',
                        'value' => hongo_get_thumbnail_image_sizes(),
                        'std' => 'full',
                        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                    ),
                    array(
                        'type' => 'hongo_custom_switch_option',
                        'heading' => esc_html__( 'Link on box', 'hongo-addons'),
                        'param_name' => 'hongo_enable_box_link',
                        'value' => array(
                            esc_html__( 'Off', 'hongo-addons') => '0', 
                            esc_html__( 'On', 'hongo-addons') => '1'
                        ),
                        'std' => '0',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Box Link / URL', 'hongo-addons'),
                        'param_name' => 'hongo_box_link_url',
                        'admin_label' => true,
                        'dependency'  => array( 'element' => 'hongo_enable_box_link', 'value' => '1' ),
                        'description' => esc_html__( 'Enter full URL with http, like http://www.example.com', 'hongo-addons' ),
                        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Box link target', 'hongo-addons'),
                        'param_name' => 'hongo_box_link_target',
                        'value' => array(
                            esc_html__('Self', 'hongo-addons') => '_self', 
                            esc_html__('New tab / window', 'hongo-addons') => '_blank'
                        ),
                        'dependency'  => array( 'element' => 'hongo_enable_box_link', 'value' => '1' ),
                        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                    ),
                ),
                'callbacks' => array(
                    'after_add' => 'vcChartParamAfterAddCallback',
                ),
                'group' => esc_html__( 'Slides', 'hongo-addons'),
                'dependency' => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Transition style', 'hongo-addons'),
                'param_name' => 'transition_style',
                'value' => array(esc_html__( 'Select transition style', 'hongo-addons') => '',
                                esc_html__( 'Slide style', 'hongo-addons') => 'slide',
                                esc_html__( 'Fade style', 'hongo-addons') => 'fade',
                                esc_html__( 'Cube style', 'hongo-addons') => 'cube',
                                esc_html__( 'Coverflow style', 'hongo-addons') => 'coverflow',
                                esc_html__( 'Flip style', 'hongo-addons') => 'flip'
                            ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2' )),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in desktop', 'hongo-addons'),
                'param_name' => 'slides_per_view_desktop',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '2.4', 'hongo-addons') => '2.4',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '3.5', 'hongo-addons') => '3.5',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '3',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mini desktop', 'hongo-addons'),
                'param_name' => 'slides_per_view_mini_desktop',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '3',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in tablet', 'hongo-addons'),
                'param_name' => 'slides_per_view_tablet',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    ),
                'std' => '2',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mobile', 'hongo-addons'),
                'param_name' => 'slides_per_view_mobile',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',                    
                    ),
                'std' => '1',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'heading' => esc_html__( 'Pagination', 'hongo-addons' ),
                'param_name' => 'hongo_show_pagination',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select ON to show pagination in slider', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Pagination style', 'hongo-addons' ),
                'param_name' => 'show_pagination_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Dot style', 'hongo-addons') => 'swiper-pagination-dots',
                    esc_html__( 'Line style', 'hongo-addons') => 'swiper-pagination-square',
                    esc_html__( 'Dot border style', 'hongo-addons') => 'swiper-pagination-border',
                ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_active_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'heading' => esc_html__( 'Navigation', 'hongo-addons' ),
                'param_name' => 'hongo_show_navigation',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'std' => '1',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
                'description' => esc_html__( 'Select ON to show navigation in slider', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Navigation color', 'hongo-addons' ),
                'param_name' => 'hongo_navigation_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_navigation', 'value' => array('1') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Cursor color style', 'hongo-addons' ),
                'param_name' => 'show_cursor_color_style',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'White cursor', 'hongo-addons') => 'white-move',
                    esc_html__( 'Black cursor', 'hongo-addons') => 'black-move',
                    esc_html__( 'Default cursor', 'hongo-addons') => 'cursor-default',
                    ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Transition speed', 'hongo-addons' ),
                'param_name' => 'slidespeed',
                'admin_label' => true,
                'value' => '',
                'description' => esc_html__( 'Enter slide speed time like 500, where 1000 = 1 second', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Autoplay', 'hongo-addons' ),
                'param_name' => 'autoplay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select On to autoplay slider', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Slide delay', 'hongo-addons' ),
                'param_name' => 'slidedelay',
                'value' => '',
                'description' => esc_html__( 'Enter delay time (before switching to other slide) like 500, where 1000 = 1 second', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'autoplay', 'value' => array('1') ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Loop', 'hongo-addons' ),
                'param_name' => 'autoloop',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'description' => esc_html__( 'Select On to autoloop slider', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-2','image-carousel-style-3' )),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Space between images', 'hongo-addons'),
                'param_name' => 'hongo_space_between_gap',
                'std' => '10',
                'description' => esc_html__( 'Enter gap value in numeric value like 10', 'hongo-addons'),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per group', 'hongo-addons'),
                'param_name' => 'slides_per_group',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                    ),
                'std' => '1',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1','image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Center slides', 'hongo-addons' ),
                'param_name' => 'hongo_center_slides',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' )),
                'description' => esc_html__( 'Note: If ON than slides per view setting not work', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'FreeMode slides', 'hongo-addons' ),
                'param_name' => 'hongo_freemode_slides',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' )),
                'description' => esc_html__( 'Note: If On then slides will not have fixed positions.', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Image box shadow', 'hongo-addons' ),
                'param_name' => 'hongo_image_box_shadow',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' )),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Background hover color', 'hongo-addons' ),
                'param_name' => 'hongo_background_hover_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1' )),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Zoom icon color', 'hongo-addons' ),
                'param_name' => 'hongo_zoom_icon_color',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1' )),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_zoom_text',
                'heading'     => esc_html__( 'Zoom text typography', 'hongo-addons' ),
                'group'        => esc_html__('Typography', 'hongo-addons'),
                'hide_element_keys' => array( 'text-hover-color', 'text-align', 'font-transform' ),
                'dependency'  => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-1' )),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_title_setting',
                'heading'    => esc_html__( 'Title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' ) ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'title_heading_tag',                
                'value' => $hongo_element_tag,
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' ) ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for title', 'hongo-addons' ),
                'param_name' => 'additional_font_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'image_gallery_type', 'value' => array( 'image-carousel-style-3' ) ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        )
    )
);