<?php
/**
 * Map For Popup
 *
 * @package hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Popup */
/*-----------------------------------------------------------------------------------*/
$date = date('Y-m-d H:i:s'); 
$time = strtotime( $date );

vc_map( 
	array(
	    'name' => esc_html__('Popup', 'hongo-addons'),
	    'description' => esc_html__('Popups with different types of content', 'hongo-addons'),
	    'icon' => 'fa-solid fa-expand hongo-shortcode-icon',
	    'base' => 'hongo_popup',
	    'category' => 'Hongo',
	    'params' => array(
	        array(
		        'type' => 'dropdown',
		        'heading' => esc_html__( 'Style', 'hongo-addons' ),
		        'param_name' => 'hongo_popup_type',
		        'admin_label' => true,
		        'value' => array(
		        	esc_html__( 'Select', 'hongo-addons') => '',
		        	esc_html__( 'Popup contact form', 'hongo-addons') => 'popup-form-1',
		        	esc_html__( 'Simple modal popup', 'hongo-addons') => 'modal-popup',
		            esc_html__( 'Youtube video', 'hongo-addons') => 'youtube-video-1',
		            esc_html__( 'Vimeo video', 'hongo-addons') => 'vimeo-video-1',
		            esc_html__( 'Google map', 'hongo-addons') => 'google-map-1',
		            esc_html__( 'Html video', 'hongo-addons') => 'html5-video-1',
		        ),
	      	),
	      	array(
		        'type' => 'hongo_preview_image',
		        'heading' => esc_html__( 'Select pre-made style for popup', 'hongo-addons' ),
		        'param_name' => 'hongo_popup_preview_image',		        
		    ),
		    array(
		        'type'        => 'textfield',
		        'heading'     => esc_html__('Button title', 'hongo-addons'),
		        'param_name'  => 'hongo_popup_button_title',
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-button','popup-icon-title' ) ),
		        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
      		),
			array(
		        'type' => 'dropdown',
		        'heading' => esc_html__( 'Button style', 'hongo-addons' ),
		        'param_name' => 'hongo_popup_styles',
		        'admin_label' => true,
		        'value' => array(
		        	esc_html__( 'Select', 'hongo-addons') => '',
		        	esc_html__( 'Button style', 'hongo-addons') => 'popup-button',
		        	esc_html__( 'Only icon style', 'hongo-addons') => 'popup-icon',
		            esc_html__( 'Icon with title style', 'hongo-addons') => 'popup-icon-title',
		        ),
		        'std' => 'popup-button',
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'popup-form-1','modal-popup','youtube-video-1','vimeo-video-1','google-map-1','html5-video-1' ) ),
		        'description' => __( 'Only icon style and icon with title style can be used in Youtube , Vimeo & HTML5 Popup', 'hongo-addons' ),
	      	),
      		array(
		        'type' => 'hongo_custom_switch_option',
		        'heading' => esc_html__('Icon – align center middle', 'hongo-addons'),
		        'param_name' => 'hongo_icon_middle',
		        'value' => array(esc_html__( 'Off', 'hongo-addons' ) => '0',
		                         esc_html__( 'On', 'hongo-addons' ) => '1'
		                        ),
		        'std' => '0',
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array('popup-icon') ),
			),
      		array(
		        'type' => 'hongo_custom_switch_option',
		        'heading' => esc_html__( 'Icon / Image', 'hongo-addons' ),
		        'param_name' => 'hongo_enable_icon',
		        'value' => array(esc_html__( 'Off', 'hongo-addons' ) => '0',
		                         esc_html__( 'On', 'hongo-addons' ) => '1'
		                        ),
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-button','popup-icon','popup-icon-title' ) ),
			),
			array(
		        'type' => 'dropdown',
		        'heading' => esc_html__( 'Icon / Image position', 'hongo-addons' ),
		        'param_name' => 'hongo_icon_image_position',
		        'value' => array(
		        	esc_html__( 'Left Side', 'hongo-addons' ) => 'icon-image-left',
		        	esc_html__( 'Right Side', 'hongo-addons' ) => 'icon-image-right',
		        ),
		        'std' => 'icon-image-left',
		        'dependency'  => array( 'element' => 'hongo_enable_icon', 'value' => array('1')),
	      	),
		    array(
		        'type' => 'hongo_custom_switch_option',
		        'heading' => esc_html__( 'Custom icon image', 'hongo-addons' ),
		        'param_name' => 'hongo_custom_icon',
		        'value' => array(esc_html__( 'Off', 'hongo-addons' ) => '0',
		                         esc_html__( 'On', 'hongo-addons' ) => '1'
		                        ),
		        'dependency'  => array( 'element' => 'hongo_enable_icon', 'value' => array('1')),
		    ),
		    array(
		        'type' => 'attach_image',
		        'heading' => esc_html__( 'Custom image', 'hongo-addons' ),
		        'param_name' => 'hongo_custom_icon_image',
		        'dependency' => array( 'element' => 'hongo_custom_icon', 'value' => '1' ),
		        'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Medium - 40px X 40px, Small - 25px X 25px, Extra Small - 18px X 18px', 'hongo-addons' ),
		    ),
		    array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Icon image maximum width', 'hongo-addons' ),
                'param_name' => 'custom_icon_max_width',
                'value' => '',
                'dependency'  => array( 'element' => 'hongo_custom_icon', 'value' => array( '1' ) ),
                'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
            ),
		    array(
		        'type' => 'dropdown',
		        'heading' => esc_html__( 'Icon size', 'hongo-addons'),
		        'param_name' => 'hongo_icon_size',
		        'admin_label' => true,
		        'value' => array( 
		        	esc_html__( 'Default','hongo-addons') => '',
		            esc_html__( 'Extra large','hongo-addons') => 'icon-extra-large', 
		            esc_html__( 'Large','hongo-addons') => 'icon-large',
		            esc_html__( 'Extra medium','hongo-addons') => 'icon-extra-medium',
		            esc_html__( 'Medium','hongo-addons') => 'icon-medium',
		            esc_html__( 'Small','hongo-addons') => 'icon-small',
		            esc_html__( 'Very small','hongo-addons') => 'icon-very-small',
		            esc_html__( 'Extra small','hongo-addons') => 'icon-extra-small',
		        ),
		        'dependency' => array( 'element' => 'hongo_custom_icon', 'value' => '0' ),
		        'std' => 'icon-medium'
		    ),
		    array(
		        'type' => 'hongo_icon',
		        'heading' => esc_html__('Font icon', 'hongo-addons'),
		        'param_name' => 'hongo_icon_list',
		        'admin_label' => true,
		        'description' => esc_html__( 'Select font type', 'hongo-addons' ),
		        'dependency' => array( 'element' => 'hongo_custom_icon', 'value' => '0' ),
		    ),
		    array(
		        'type' => 'dropdown',
		        'heading' => esc_html__( 'Select form', 'hongo-addons' ),
		        'param_name' => 'hongo_contact_forms_shortcode',
		        'value' => $contact_forms,
		        'description' => esc_html__( 'Select your desired form generated using contact form 7 plugin to make it visible in the popup.', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'popup-form-1' ) ),
		    ),
		    array(
		        'type' => 'textfield',
		        'heading' => esc_html__('Popup title', 'hongo-addons'),
		        'param_name' => 'hongo_inside_popup_title',
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),
		        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
		    ),
	      	array(
	        	'type' => 'textarea_html',
	        	'heading' => esc_html__('Popup content', 'hongo-addons'),
	        	'param_name' => 'content',
	        	'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),
	    	),
	    	array(
		        'type' => 'textfield',
		        'std'  => esc_html__( 'DISMISS','hongo-addons' ),
		        'heading' => esc_html__('Dismiss text', 'hongo-addons'),
		        'param_name' => 'hongo_dismiss_text',
		        'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),
		    ),
		    array(
		        'type' => 'textfield',
		        'heading' => esc_html__('Popup ID', 'hongo-addons'),
		        'param_name' => 'hongo_popup_form_id',
		        'value' => $time,
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'popup-form-1','modal-popup','html5-video-1' ) ),
		    ),
		    array(
		        'type' => 'dropdown',
		        'heading' => esc_html__('Animation style', 'hongo-addons'),
		        'param_name' => 'hongo_popup_animation_effect',
		        'value' => array(esc_html__('Select', 'hongo-addons') => '',
		                  esc_html__('Move animation', 'hongo-addons') => 'popup-with-move-anim',
		                  esc_html__('Zoom animation', 'hongo-addons') => 'popup-with-zoom-anim',
		        ),
		        'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),
		    ),
		    array(
		        'type' => 'textfield',
		        'heading' => esc_html__('YouTube URL', 'hongo-addons'),
		        'param_name' => 'hongo_popup_youtube_url',
		        'description' => esc_html__( 'Add YOUTUBE VIDEO URL like https://www.youtube.com/watch?v=xxxxxxxxxx, you will get this from youtube.', 'hongo-addons' ),
		        'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'youtube-video-1' ) ),
		    ),
		    array(
		        'type' => 'textfield',
		        'heading' => esc_html__('Vimeo URL', 'hongo-addons'),
		        'param_name' => 'hongo_popup_vimeo_url',
		        'description' => esc_html__( 'Add VIMEO VIDEO URL like https://player.vimeo.com/video/xxxxxxxxxx, you will get this from vimeo.', 'hongo-addons' ),
		        'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'vimeo-video-1' ) ),
		    ),
		    array(
		        'type' => 'textfield',
		        'heading' => esc_html__('Google map URL', 'hongo-addons'),
		        'param_name' => 'hongo_popup_google_map_url',
		        'description' => esc_html__( 'Add GOOGLE MAP URL like https://www.google.com/maps/embed?pb=xxxxxxxxxx, you will get this from google map.', 'hongo-addons' ),
		        'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'google-map-1' ) ),
		    ),
			array(
				'type' => 'colorpicker',
				'class' => '',
				'heading' => esc_html__( 'Icon color', 'hongo-addons' ),
				'param_name' => 'hongo_icon_color',
				'dependency' => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-icon' )),
				'group' => esc_html__( 'Style', 'hongo-addons' ),
			),
			array(
				'type' => 'colorpicker',
				'class' => '',
				'heading' => esc_html__( 'Icon Border color', 'hongo-addons' ),
				'param_name' => 'hongo_icon_border_color',
				'dependency' => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-icon' )),
				'group' => esc_html__( 'Style', 'hongo-addons' ),
			),
		    array(
              	'type' => 'textfield',
              	'heading' => esc_html__('MP4 URL', 'hongo-addons'),
              	'param_name' => 'hongo_mp4_video',
              	'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array( 'html5-video-1' ) ),
              	'group' => esc_html__( 'Video Url', 'hongo-addons' ),
          	),
	        array(
	        	'type' => 'textfield',
	            'heading' => esc_html__( 'WEBM URL', 'hongo-addons' ),
	            'param_name' => 'hongo_webm_video',
	            'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array('html5-video-1') ),
	            'group' => esc_html__( 'Video Url', 'hongo-addons' ),
	        ),
          	array(
              	'type' => 'textfield',
              	'heading' => esc_html__('OGG URL', 'hongo-addons'),
              	'param_name' => 'hongo_ogg_video',
              	'dependency' => array( 'element' => 'hongo_popup_type', 'value' => array('html5-video-1') ),
              	'group' => esc_html__( 'Video Url', 'hongo-addons' ),
          	),
			array(
		        'type'        => 'responsive_font_settings',
		        'param_name'  => 'hongo_font_title_setting',
		        'hide_element_keys' => array( 'text-hover-color' ),
		        'heading'     => esc_html__( 'Popup title typography', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),		        
		        'group' => esc_html__( 'Typography', 'hongo-addons' ),
			),
			array(
		        'type'        => 'responsive_font_settings',
		        'param_name'  => 'hongo_font_content_setting',
		        'heading'     => esc_html__( 'Popup content typography', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'modal-popup' ) ),
		        'group' => esc_html__( 'Typography', 'hongo-addons' ),
		        'hide_element_keys' => array( 'text-hover-color' ),
			),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Black', 'hongo-addons') => 'style1',
                    esc_html__('White', 'hongo-addons') => 'style2',
                    esc_html__('Base color', 'hongo-addons') => 'style10',
                    esc_html__('Black border', 'hongo-addons') => 'style3',
                    esc_html__('White border', 'hongo-addons') => 'style4',
                    esc_html__('Base color border', 'hongo-addons') => 'style11',
                    esc_html__('Black round corner', 'hongo-addons') => 'style5',
                    esc_html__('White round corner', 'hongo-addons') => 'style6',
                    esc_html__('Base color round corner', 'hongo-addons') => 'style12',
                    esc_html__('Black border with rounded', 'hongo-addons') => 'style7',
                    esc_html__('White border with rounded', 'hongo-addons') => 'style8',
                    esc_html__('Base color border with rounded', 'hongo-addons') => 'style13',
                    esc_html__('Text with underline', 'hongo-addons') => 'style9',
                    esc_html__('Base color text with underline', 'hongo-addons') => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-button', 'popup-icon-title' ) ),
            ),
            array(
		        'type' => 'dropdown',
		        'heading' => esc_html__('Button size', 'hongo-addons'),
		        'param_name' => 'hongo_button_size',
		        'value' => array(esc_html__('Select', 'hongo-addons') => '',
		                  esc_html__('Extra large', 'hongo-addons') => 'btn-extra-large',
		                  esc_html__('Large', 'hongo-addons') => 'btn-large',
		                  esc_html__('Medium', 'hongo-addons') => 'btn-medium',
		                  esc_html__('Small', 'hongo-addons') => 'btn-small',
		                  esc_html__('Very small', 'hongo-addons') => 'btn-very-small',
		        ),
		        'std' => 'btn-medium',
		        'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-button' ) ),
		    ),
			array(
		        'type' => 'hongo_button_settings',
		        'param_name' => 'hongo_font_button_setting',
		        'heading' => esc_html__( 'Button typography', 'hongo-addons' ),
		        'group' => esc_html__( 'Button Settings', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_styles', 'value' => array( 'popup-button','popup-icon-title' ) ),
			),
			array(
		        'type' => 'dropdown',
		        'heading' => esc_html__('SM Width', 'hongo-addons' ),
		        'param_name' => 'hongo_width',
		        'value' => $hongo_vc_column,
		        'group' => esc_html__( 'Responsive Options', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array( 'popup-form-1','modal-popup' ) ),
		        'description' => esc_html__( 'Select column width', 'hongo-addons' ),
		    ),
		    array(
		        'type' => 'column_offset',
		        'heading' => esc_html__( 'Responsiveness', 'hongo-addons' ),
		        'param_name' => 'hongo_offset',
		        'group' => esc_html__( 'Responsive Options', 'hongo-addons' ),
		        'description' => esc_html__( 'Adjust column for different screen sizes. Control width, offset and visibility settings.', 'hongo-addons' ),
		        'dependency'  => array( 'element' => 'hongo_popup_type', 'value' => array('popup-form-1','modal-popup') ),
		    ),
		    $hongo_vc_extra_id,
      		$hongo_vc_extra_class,
	    )
	)
);