<?php
/**
  * Map For Shop Banner
  *
  * @package Hongo
  */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Shop Banner */
/*-----------------------------------------------------------------------------------*/
vc_map( 
    array(
        'name' => esc_html__( 'Shop Banner', 'hongo-addons' ),
        'base' => 'hongo_shop_banner',
        'category' => 'Hongo',
        'description' => esc_html__( 'Add promotional shopping banners', 'hongo-addons' ),
        'icon' => 'fa-solid fa-image hongo-shortcode-icon',
        'params' => array(
            array(
                'type'        => 'dropdown',
                'heading'     => esc_html__( 'Style', 'hongo-addons' ),
                'param_name'  => 'hongo_shop_banner_style',
                'admin_label' => true,
                'value'       => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Shop Banner Style 1', 'hongo-addons')  => 'hongo-shop-banner-1',
                    esc_html__( 'Shop Banner Style 2', 'hongo-addons')  => 'hongo-shop-banner-4',
                    esc_html__( 'Shop Banner Style 3', 'hongo-addons')  => 'hongo-shop-banner-11',
                    esc_html__( 'Shop Banner Style 4', 'hongo-addons')  => 'hongo-shop-banner-6',
                    esc_html__( 'Shop Banner Style 5', 'hongo-addons')  => 'hongo-shop-banner-14',
                    esc_html__( 'Shop Banner Style 6', 'hongo-addons')  => 'hongo-shop-banner-15',
                    esc_html__( 'Shop Banner Style 7', 'hongo-addons')  => 'hongo-shop-banner-16',
                    esc_html__( 'Shop Banner Style 8', 'hongo-addons')  => 'hongo-shop-banner-5',                    
                    esc_html__( 'Shop Banner Style 9', 'hongo-addons')  => 'hongo-shop-banner-20',                    
                    esc_html__( 'Shop Banner Style 10', 'hongo-addons') => 'hongo-shop-banner-3',
                    esc_html__( 'Shop Banner Style 11', 'hongo-addons') => 'hongo-shop-banner-7',
                    esc_html__( 'Shop Banner Style 12', 'hongo-addons') => 'hongo-shop-banner-8',
                    esc_html__( 'Shop Banner Style 13', 'hongo-addons') => 'hongo-shop-banner-9',
                    esc_html__( 'Shop Banner Style 14', 'hongo-addons') => 'hongo-shop-banner-10',
                ),
            ),
            array(
                'type'       => 'hongo_preview_image',
                'heading'    => esc_html__( 'Select pre-made style for Shop Banner', 'hongo-addons'),
                'param_name' => 'hongo_shop_banner_preview_image',
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Separator', 'hongo-addons'),
                'param_name' => 'hongo_separator',
                'std'        => '1',
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-8','hongo-shop-banner-15' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Content position', 'hongo-addons' ),
                'param_name' => 'content_position',
                'value' => array( 
                    esc_html__( 'Default', 'hongo-addons') => '',
                    esc_html__( 'Left', 'hongo-addons') => 'left-side-product',
                    esc_html__( 'Center', 'hongo-addons' ) => 'center-side-product',
                    esc_html__( 'Right', 'hongo-addons' ) => 'right-side-product',
                ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Content width', 'hongo-addons' ),
                'param_name' => 'content_width',
                'value' => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-16' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Content position', 'hongo-addons' ),
                'param_name' => 'content_position_without_center',
                'value' => array( 
                    esc_html__( 'Default', 'hongo-addons') => '',
                    esc_html__( 'Left', 'hongo-addons') => 'left-side-product',
                    esc_html__( 'Right', 'hongo-addons' ) => 'right-side-product',
                ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10' ) ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Title', 'hongo-addons'),
                'param_name' => 'hongo_title',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7','hongo-shop-banner-8','hongo-shop-banner-9', 'hongo-shop-banner-10' , 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20') ),
                'description'=> esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),            
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Subtitle', 'hongo-addons'),
                'param_name' => 'hongo_subtitle',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7','hongo-shop-banner-8', 'hongo-shop-banner-10',  'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16') ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Highlight text', 'hongo-addons'),
                'param_name' => 'hongo_highlight_text',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-15' ) ),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Content title text', 'hongo-addons'),
                'param_name' => 'hongo_content_title_text',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-14', 'hongo-shop-banner-15' ) ),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type'       => 'textarea_html',
                'heading'    => esc_html__( 'Content', 'hongo-addons' ),
                'param_name' => 'content',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-10','hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15','hongo-shop-banner-16' ) ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Regular price', 'hongo-addons'),
                'param_name' => 'hongo_regular_price',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-11' ) ),
                'description'=> esc_html__( 'Enter Regular Price', 'hongo-addons' ),
            ),
            array(
                'type'       => 'textfield',
                'heading'    => esc_html__( 'Sale price', 'hongo-addons'),
                'param_name' => 'hongo_sale_price',
                'value'      => '',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-11' ) ),
                'description'=> esc_html__( 'Enter Sale Price', 'hongo-addons' ),
            ),
            array(
                'type'       => 'attach_image',
                'heading'    => esc_html__( 'Image', 'hongo-addons' ),
                'param_name' => 'hongo_image',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-3', 'hongo-shop-banner-5', 'hongo-shop-banner-7','hongo-shop-banner-8','hongo-shop-banner-9', 'hongo-shop-banner-10' ) ),
            ),
            array(
                'type'       => 'dropdown',
                'heading'    => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                'param_name' => 'hongo_image_srcset',
                'value'      => hongo_get_thumbnail_image_sizes(),
                'std'        => 'full',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-3', 'hongo-shop-banner-5', 'hongo-shop-banner-7','hongo-shop-banner-8','hongo-shop-banner-9', 'hongo-shop-banner-10' ) ),
            ),
            array(
                'type'       => 'vc_link',
                'heading'    => esc_html__( 'Button configuration', 'hongo-addons' ),
                'param_name' => 'hongo_button',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7','hongo-shop-banner-8','hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3', 'hongo-shop-banner-5') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Button icon', 'hongo-addons'),
                'param_name' => 'hongo_button_enable_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7','hongo-shop-banner-8','hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3') ),
            ),            
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Button icon size', 'hongo-addons' ),
                'param_name' => 'hongo_button_icon_type',
                'value' => array(
                    esc_html__('Select', 'hongo-addons') => '',
                    esc_html__('Extra large', 'hongo-addons') => 'icon-extra-large',
                    esc_html__('Large', 'hongo-addons') => 'icon-large',
                    esc_html__('Extra medium', 'hongo-addons') => 'icon-extra-medium',
                    esc_html__('Medium', 'hongo-addons') => 'icon-medium',
                    esc_html__('Extra small', 'hongo-addons') => 'icon-extra-small',
                    esc_html__('Small', 'hongo-addons') => 'icon-small',
                    esc_html__('Very small', 'hongo-addons') => 'icon-very-small',
                ),
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => '1' ),
                'edit_field_class' => 'vc_col-sm-6'
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button icon position', 'hongo-addons'),
                'param_name' => 'hongo_button_icon_position',
                'value' => array(
                    esc_html__('Left', 'hongo-addons') => 'left',
                    esc_html__('Right', 'hongo-addons') => 'right',
                ),
                'std' => 'left',
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => array( '1' ) ),
                'edit_field_class' => 'vc_col-sm-6'
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__('Button font icon', 'hongo-addons'),
                'param_name' => 'hongo_button_icon',
                'admin_label' => true,
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => '1' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__('Image effect on hover', 'hongo-addons'),
                'param_name' => 'hongo_image_hover_effect',
                'value' => array(
                    esc_html__('Off', 'hongo-addons') => '0',
                    esc_html__('On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-5') ),
            ),            
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Background color', 'hongo-addons' ),
                'param_name' => 'hongo_background_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-6', 'hongo-shop-banner-7','hongo-shop-banner-8', 'hongo-shop-banner-11', 'hongo-shop-banner-10','hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-20','hongo-shop-banner-9') ),
            ),
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Background hover color', 'hongo-addons' ),
                'param_name' => 'hongo_background_hover_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-9' ) ),
            ),
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Separator color', 'hongo-addons' ),
                'param_name' => 'hongo_separator_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_separator', 'value' => array( '1' ) ),
            ),
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Highlight background color', 'hongo-addons' ),
                'param_name' => 'hongo_highlight_bg_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-15' ) ),
            ),
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Subtitle separator color', 'hongo-addons' ),
                'param_name' => 'hongo_subtitle_separator_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-11' ) ),
            ),
            array(
                'type'       => 'colorpicker',
                'class'      => '',
                'heading'    => esc_html__( 'Box gradient color', 'hongo-addons' ),
                'param_name' => 'hongo_box_gradient_color',
                'group'      => esc_html__( 'Style', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-5' ) ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__('Default', 'hongo-addons') => '',
                    esc_html__('Black', 'hongo-addons') => 'style1',
                    esc_html__('White', 'hongo-addons') => 'style2',
                    esc_html__('Base color', 'hongo-addons') => 'style10',
                    esc_html__('Black border', 'hongo-addons') => 'style3',
                    esc_html__('White border', 'hongo-addons') => 'style4',
                    esc_html__('Base color border', 'hongo-addons') => 'style11',
                    esc_html__('Black round corner', 'hongo-addons') => 'style5',
                    esc_html__('White round corner', 'hongo-addons') => 'style6',
                    esc_html__('Base color round corner', 'hongo-addons') => 'style12',
                    esc_html__('Black border with rounded', 'hongo-addons') => 'style7',
                    esc_html__('White border with rounded', 'hongo-addons') => 'style8',
                    esc_html__('Base color border with rounded', 'hongo-addons') => 'style13',
                    esc_html__('Text with underline', 'hongo-addons') => 'style9',
                    esc_html__('Base color text with underline', 'hongo-addons') => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-5','hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button size', 'hongo-addons'),
                'param_name' => 'hongo_button_type',
                'value' => array(
                    esc_html__('Select', 'hongo-addons') => '',
                    esc_html__('Extra large', 'hongo-addons') => 'btn-extra-large',
                    esc_html__('Large', 'hongo-addons') => 'btn-large',
                    esc_html__('Medium', 'hongo-addons') => 'btn-medium',
                    esc_html__('Small', 'hongo-addons') => 'btn-small',
                    esc_html__('Very small', 'hongo-addons') => 'btn-very-small',
                ),
                'edit_field_class' => 'vc_col-sm-6 button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-5', 'hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3') ),
            ),
            array(
                'type'       => 'hongo_button_settings',
                'param_name' => 'hongo_button_setting',
                'heading'    => esc_html__( 'Button typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4','hongo-shop-banner-5', 'hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3') ),
            ),            
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_title_setting',
                'heading'    => esc_html__( 'Title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4','hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20') ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'title_heading_tag',
                'value' => $hongo_element_tag,
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4','hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9' , 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20') ),
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Use additional font for title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_title',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std'        => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'description'=> esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4','hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-9', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16','hongo-shop-banner-20') ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_subtitle_setting',
                'heading'    => esc_html__( 'Subtitle typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16') ),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Subtitle element tag', 'hongo-addons'),
                'param_name' => 'subtitle_heading_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16') ),
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'heading'    => esc_html__( 'Use additional font for subtitle', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_subtitle',
                'value'      => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std'        => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description'=> esc_html__( 'If On is selected then subtitle will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-6', 'hongo-shop-banner-7', 'hongo-shop-banner-8', 'hongo-shop-banner-10', 'hongo-shop-banner-11', 'hongo-shop-banner-14','hongo-shop-banner-15', 'hongo-shop-banner-16') )
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_content_title_setting',
                'heading'    => esc_html__( 'Content title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-14','hongo-shop-banner-15') ), 
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_content_setting',
                'heading'    => esc_html__( 'Content typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-1', 'hongo-shop-banner-10','hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16') ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_hightlight_setting',
                'heading'    => esc_html__( 'Highlight text typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-15' ) ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_regular_price_setting',
                'heading'    => esc_html__( 'Regular price typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-11' ) ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_sale_price_setting',
                'heading'    => esc_html__( 'Sale price typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform', 'text-align' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array( 'hongo-shop-banner-11' ) ),
            ),
            array(
                'type'       => 'css_editor',
                'heading'    => esc_html__( 'CSS box', 'hongo-addons' ),
                'param_name' => 'css',
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1','hongo-shop-banner-4','hongo-shop-banner-5','hongo-shop-banner-6', 'hongo-shop-banner-9', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3' )),
            ),
            array(
                'type'       => 'dropdown',
                'param_name' => 'hongo_bg_image_type', 
                'heading'    => esc_html__( 'Background type', 'hongo-addons' ),
                'value'      => array(esc_html__('Select background type', 'hongo-addons') => '',
                               esc_html__('Fix background', 'hongo-addons') => 'fix-background',
                               esc_html__('Cover background', 'hongo-addons') => 'cover-background',
                              ),
                'edit_field_class' => 'vc_col-sm-3 vc_column-with-padding',
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1','hongo-shop-banner-6', 'hongo-shop-banner-9', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16','hongo-shop-banner-20', 'hongo-shop-banner-3')),
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
                'type'       => 'dropdown',
                'heading'    => esc_html__( 'Background position', 'hongo-addons' ),
                'param_name' => 'desktop_bg_image_position',
                'value'      => $hongo_desktop_bg_image_position,
                'edit_field_class' => 'vc_col-sm-3',
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1','hongo-shop-banner-4','hongo-shop-banner-6', 'hongo-shop-banner-9', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16','hongo-shop-banner-20', 'hongo-shop-banner-3')),
            ),
            array(
                'param_name' => 'hongo_custom_separator_heading',
                'type'       => 'hongo_custom_title',
                'value'      => '',
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1','hongo-shop-banner-4', 'hongo-shop-banner-5','hongo-shop-banner-6', 'hongo-shop-banner-9', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3')),
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_width',
                'heading' => esc_html__( 'Box content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-16')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_mini_width',
                'heading' => esc_html__( 'Box content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-16')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_ipad_width',
                'heading' => esc_html__( 'Box content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-16')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_mobile_width',
                'heading' => esc_html__( 'Box content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1', 'hongo-shop-banner-4', 'hongo-shop-banner-16')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_content_desktop_width',
                'heading' => esc_html__( 'Content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-10')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_content_desktop_mini_width',
                'heading' => esc_html__( 'Content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-10')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_content_ipad_width',
                'heading' => esc_html__( 'Content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-10')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_content_mobile_width',
                'heading' => esc_html__( 'Content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency'  => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-10')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type'       => 'hongo_custom_switch_option',
                'holder'     => 'div',
                'class'      => '',
                'heading'    => esc_html__( 'Enable responsive css', 'hongo-addons'),
                'param_name' => 'hongo_enable_responsive_css',
                'value'      => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                                esc_html__( 'On', 'hongo-addons') => '1'
                              ),
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_shop_banner_style', 'value' => array('hongo-shop-banner-1','hongo-shop-banner-4','hongo-shop-banner-5','hongo-shop-banner-6', 'hongo-shop-banner-9', 'hongo-shop-banner-11', 'hongo-shop-banner-14', 'hongo-shop-banner-15', 'hongo-shop-banner-16', 'hongo-shop-banner-20', 'hongo-shop-banner-3')),
            ),
            array(
                'type'       => 'responsive_css_editor',
                'heading'    => esc_html__( 'Responsive css box', 'hongo-addons' ),
                'param_name' => 'responsive_css',
                'width'      => 'no',
                'height'     => 'no',
                'dependency' => array( 'element' => 'hongo_enable_responsive_css', 'value' => array('1') ),
                'group'      => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        ),
    ) 
);