<?php
/**
 * Shortcode Map For Team Member Slider
 *
 * @package Hongo
 */
?>
<?php 
/*-----------------------------------------------------------------------------------*/
/* Team Member Slider */
/*-----------------------------------------------------------------------------------*/
vc_map( 
    array(
    	'icon' => 'hongo-shortcode-icon fa-solid fa-users',
        'name' => esc_html__('Team Member Slider', 'hongo-addons'),
        'base' => 'hongo_team_member_slider',
        'description' => esc_html__( 'Slideshow of team member profiles', 'hongo-addons' ),
        'category' => 'Hongo',
        'content_element' => true,
        'params' => array( 
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons'),
                'param_name' => 'hongo_team_member_slider_style',
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Style 1', 'hongo-addons') => 'team-slider-style-1',
                    esc_html__( 'Style 2', 'hongo-addons') => 'team-slider-style-2',
                    esc_html__( 'Style 3', 'hongo-addons') => 'team-slider-style-3',
                    esc_html__( 'Style 4', 'hongo-addons') => 'team-slider-style-4',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__( 'Select pre-made style for block', 'hongo-addons'),
                'param_name' => 'hongo_team_member_slider_preview_image',
            ),
            array(
                'type'       => 'hongo_custom_social_sorting',
                'heading'    => esc_html__( 'Social sorting', 'hongo-addons'),
                'param_name' => 'hongo_social_sorting',
                'value' => array(
                    esc_html__( 'Facebook', 'hongo-addons')      => 'facebook',
                    esc_html__( 'Twitter', 'hongo-addons')       => 'twitter',
                    esc_html__( 'Dribbble', 'hongo-addons')      => 'dribbble',
                    esc_html__( 'LinkedIn', 'hongo-addons')      => 'linkedin',
                    esc_html__( 'Instagram', 'hongo-addons')     => 'instagram',
                    esc_html__( 'Tumblr', 'hongo-addons')        => 'tumblr',
                    esc_html__( 'Pinterest', 'hongo-addons')     => 'pinterest',
                    esc_html__( 'Youtube', 'hongo-addons')       => 'youtube',
                    esc_html__( 'Vimeo', 'hongo-addons')         => 'vimeo',
                    esc_html__( 'Soundcloud', 'hongo-addons')    => 'soundcloud',
                    esc_html__( 'Flickr', 'hongo-addons')        => 'flickr',
                    esc_html__( 'RSS', 'hongo-addons')           => 'rss',
                    esc_html__( 'Reddit', 'hongo-addons')        => 'reddit',
                    esc_html__( 'Behance', 'hongo-addons')       => 'behance',
                    esc_html__( 'Vine', 'hongo-addons')          => 'vine',
                    esc_html__( 'GitHub', 'hongo-addons')        => 'github',
                    esc_html__( 'Xing', 'hongo-addons')          => 'xing',
                    esc_html__( 'VK', 'hongo-addons')            => 'vk',
                    esc_html__( 'Yelp', 'hongo-addons')          => 'yelp',
                    esc_html__( 'Discord', 'hongo-addons')       => 'discord',
                    esc_html__( 'Skype', 'hongo-addons')         => 'skype',
                    esc_html__( 'Email address', 'hongo-addons') => 'email',
                ),
                'std' => '',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'group'       => esc_html__( 'Slides', 'hongo-addons'),
            ),
            array(
                'param_name' => 'hongo_team_member_slides', // all params must have a unique name
                'type' => 'param_group', // this param type
                'heading' => esc_html__( 'Slide', 'hongo-addons' ),
                'value' => '',
                'params' => array(
                    array(
                        'type' => 'attach_image',
                        'heading' => esc_html__( 'Image', 'hongo-addons' ),
                        'param_name' => 'hongo_image',
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                        'param_name' => 'hongo_image_srcset',
                        'value' => hongo_get_thumbnail_image_sizes(),
                        'std' => 'full',
                        'edit_field_class' => 'vc_col-sm-4',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Name', 'hongo-addons'),
                        'param_name' => 'hongo_member_name',
                        'admin_label' => true,
                        'edit_field_class' => 'vc_col-sm-4',
                        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons'),
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Designation / Content', 'hongo-addons'),
                        'param_name' => 'hongo_member_des',
                        'admin_label' => true,
                        'edit_field_class' => 'vc_col-sm-4',
                        'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
                    ),
                    array(
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Name link target', 'hongo-addons'),
                        'param_name' => 'hongo_link_target',
                        'value' => array(
                            esc_html__('Self', 'hongo-addons') => '_self', 
                            esc_html__('New tab / window', 'hongo-addons') => '_blank',
                            esc_html__('One page', 'hongo-addons') => 'one_page',
                        ),
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type' => 'textfield',
                        'heading' =>esc_html__( 'Name link / URL', 'hongo-addons'),
                        'param_name' => 'hongo_link_url',
                        'admin_label' => true,
                        'edit_field_class' => 'vc_col-sm-6',
                        'description' => esc_html__( 'Enter full URL with http, like http://www.example.com', 'hongo-addons' ),
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Facebook URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_facebook_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Twitter URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_twitter_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Dribbble URL', 'hongo-addons'),
                        'param_name'  => 'hongo_db_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'LinkedIn URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_linkedin_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Instagram URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_instagram_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Tumblr URL', 'hongo-addons'),
                        'param_name'  => 'hongo_tb_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Pinterest URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_pinterest_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Youtube URL', 'hongo-addons'),
                        'param_name'  => 'hongo_yt_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Vimeo URL', 'hongo-addons'),
                        'param_name'  => 'hongo_vm_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Soundcloud URL', 'hongo-addons'),
                        'param_name'  => 'hongo_sc_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Flickr URL', 'hongo-addons'),
                        'param_name'  => 'hongo_fk_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('RSS URL', 'hongo-addons'),
                        'param_name'  => 'hongo_rss_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Reddit URL', 'hongo-addons'),
                        'param_name'  => 'hongo_rd_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__( 'Behance URL', 'hongo-addons' ),
                        'param_name'  => 'hongo_behance_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Vine URL', 'hongo-addons'),
                        'param_name'  => 'hongo_vine_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('GitHub URL', 'hongo-addons'),
                        'param_name'  => 'hongo_gh_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Xing URL', 'hongo-addons'),
                        'param_name'  => 'hongo_xing_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('VK URL', 'hongo-addons'),
                        'param_name'  => 'hongo_vk_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Yelp URL', 'hongo-addons'),
                        'param_name'  => 'hongo_yelp_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Discord URL', 'hongo-addons'),
                        'param_name'  => 'hongo_discord_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Skype URL', 'hongo-addons'),
                        'param_name'  => 'hongo_skype_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textfield',
                        'heading'     => esc_html__('Email address', 'hongo-addons'),
                        'param_name'  => 'hongo_email_url',
                        'edit_field_class' => 'vc_col-sm-6',
                    ),
                    array(
                        'type'        => 'textarea_raw_html',
                        'heading'     => esc_html__( 'Custom icons code', 'hongo-addons' ),
                        'value'      => base64_encode( 'CustomHTML' ),
                        'param_name'  => 'hongo_custom_link',
                    ),
                ),
                'callbacks' => array(
                    'after_add' => 'vcChartParamAfterAddCallback',
                ),
                'group' => esc_html__( 'Slides', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
			array(
				'type' => 'hongo_custom_switch_option',
				'holder' => 'div',
				'class' => '',
				'heading' => esc_html__( 'Pagination', 'hongo-addons'),
				'param_name' => 'hongo_show_pagination',
				'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
				    esc_html__( 'On', 'hongo-addons') => '1'
				),
				'std' => '1',
				'description' => esc_html__( 'Select ON to show pagination in slider', 'hongo-addons' ),
				'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
				'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Pagination style', 'hongo-addons'),
				'param_name' => 'hongo_show_pagination_style',
				'admin_label' => true,
				'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Dot style', 'hongo-addons') => 'swiper-pagination-dots',
                    esc_html__( 'Line style', 'hongo-addons') => 'swiper-pagination-square',
                    esc_html__( 'Dot border style', 'hongo-addons') => 'swiper-pagination-border',
                ),
				'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
				'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active pagination color', 'hongo-addons' ),
                'param_name' => 'hongo_active_pagination_color',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
            ),
            array(
				'type' => 'dropdown',
				'heading' => esc_html__( 'Cursor color style', 'hongo-addons'),
				'param_name' => 'hongo_show_cursor_color_style',
				'admin_label' => true,
				'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
				    esc_html__( 'White cursor', 'hongo-addons') => 'white-move',
				    esc_html__( 'Black cursor', 'hongo-addons') => 'black-move',
				    esc_html__( 'Default cursor', 'hongo-addons') => 'cursor-default',
				),
				'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
				'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array( 'team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4' ) ),
            ),
			array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Transition speed', 'hongo-addons'),
                'param_name' => 'hongo_slidespeed',
                'value' => '',
                'description' => esc_html__( 'Enter slide speed time like 500, where 1000 = 1 second', 'hongo-addons'),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Autoplay', 'hongo-addons'),
                'param_name' => 'hongo_autoplay',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'description' => esc_html__( 'Select On to autoplay slider', 'hongo-addons' ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Slide delay', 'hongo-addons'),
                'param_name' => 'hongo_slidedelay',
                'admin_label' => true,
                'value' => '',
                'description' => esc_html__( 'Enter delay time (before switching to other slide) like 500, where 1000 = 1 second', 'hongo-addons'),
                'dependency'  => array( 'element' => 'hongo_autoplay', 'value' => array('1') ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'holder' => 'div',
                'class' => '',
                'heading' => esc_html__( 'Loop', 'hongo-addons'),
                'param_name' => 'hongo_autoloop',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Space between slides', 'hongo-addons'),
                'param_name' => 'hongo_space_between_gap',
                'std' => '30',
                'description' => esc_html__( 'Enter gap value in numeric value like 10', 'hongo-addons'),
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in desktop', 'hongo-addons'),
                'param_name' => 'hongo_slides_per_view_desktop',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                ),
                'std' => '4',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mini desktop', 'hongo-addons'),
                'param_name' => 'hongo_slides_per_view_mini_desktop',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                ),
                'std' => '3',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in tablet', 'hongo-addons'),
                'param_name' => 'hongo_slides_per_view_tablet',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                ),
                'std' => '2',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Slides per view in mobile', 'hongo-addons'),
                'param_name' => 'hongo_slides_per_view_mobile',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( '1', 'hongo-addons') => '1',
                    esc_html__( '2', 'hongo-addons') => '2',
                    esc_html__( '3', 'hongo-addons') => '3',
                    esc_html__( '4', 'hongo-addons') => '4',
                    esc_html__( '5', 'hongo-addons') => '5',
                    esc_html__( '6', 'hongo-addons') => '6',
                ),
                'std' => '1',
                'group' => esc_html__( 'Slider Configuration', 'hongo-addons'),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'class' => '',
                'heading' => esc_html__( 'Separator', 'hongo-addons' ),
                'param_name' => 'hongo_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-4') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Separator Color', 'hongo-addons' ),
                'param_name' => 'hongo_separator_color',
                'dependency' => array( 'element' => 'hongo_enable_separator', 'value' => array('1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box content background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_content_bg_color',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box hover background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_hover_bg_color',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box hover gradient background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_hover_gradient_bg_color',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array( 'team-slider-style-4' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Social icon size', 'hongo-addons'),
                'param_name' => 'hongo_social_icon_size',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Default', 'hongo-addons') => '',
                    esc_html__( 'Extra large', 'hongo-addons') => 'icon-extra-large', 
                    esc_html__( 'Large', 'hongo-addons') => 'icon-large',
                    esc_html__( 'Extra medium', 'hongo-addons') => 'icon-extra-medium',
                    esc_html__( 'Medium', 'hongo-addons') => 'icon-medium',
                    esc_html__( 'Small', 'hongo-addons') => 'icon-small',
                    esc_html__( 'Extra small', 'hongo-addons') => 'icon-extra-small',
                ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Social icon color', 'hongo-addons' ),
                'param_name' => 'hongo_social_icon_color',
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_name_setting',
                'heading'     => esc_html__( 'Name typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Name element tag', 'hongo-addons'),
                'param_name' => 'name_heading_tag',
                'value' => $hongo_element_tag,
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for name', 'hongo-addons' ),
                'param_name' => 'additional_font_name',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description' => esc_html__( 'If On is selected then name will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_designation_setting',
                'heading'     => esc_html__( 'Designation / Content typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Designation element tag', 'hongo-addons'),
                'param_name' => 'designation_heading_tag',
                'value' => $hongo_element_tag,
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for designation', 'hongo-addons' ),
                'param_name' => 'additional_font_designation',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description' => esc_html__( 'If On is selected then designation will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_team_member_slider_style', 'value' => array('team-slider-style-1','team-slider-style-2','team-slider-style-3','team-slider-style-4') ),
            ), 
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Element ID', 'hongo-addons' ),
                'description' => sprintf( esc_html__( 'Enter element ID (Note: make sure it is unique and valid according to %s).', 'hongo-addons'), '<a target="_blank" href="https://www.w3schools.com/tags/att_global_id.asp">w3c specification</a>'),
                'param_name'  => 'hongo_slider_id',
                'group'       => esc_html__( 'Extras', 'hongo-addons' )
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Extra class name', 'hongo-addons' ),
                'description' => esc_html__( 'Add additional CSS class to this element, you can define multiple CSS class with use of space like "Class1 Class2". You can write css code using this class and add it in customizer or your child theme css file.', 'hongo-addons' ),
                'param_name'  => 'hongo_slider_class',
                'group'       => esc_html__( 'Extras', 'hongo-addons' )
            ),
    	)
    )
);