<?php
/**
 * Shortcode Map For Inner Column
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Column & Inner Column */
/*-----------------------------------------------------------------------------------*/

vc_map(
    array(
        'name' => esc_html__( 'Inner Column', 'hongo-addons' ),
        'base' => 'vc_column_inner',
        'description' => esc_html__( 'Place content elements inside the column', 'hongo-addons' ),
        'icon' => 'icon-wpb-row',
        'is_container' => true,
        'content_element' => false,
        'allowed_container_element' => false,
        'category' => 'Hongo',
        'js_view' => 'VcColumnView',
        'params' => array(
            array(
              'type' => 'hongo_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => esc_html__( 'Fullscreen class', 'hongo-addons'),
              'param_name' => 'fullscreen',
              'value' => array(esc_html__( 'Off', 'hongo-addons') => '0',
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
              'description' => esc_html__( 'Select On to add (full-screen) class in this column', 'hongo-addons' ),
            ),
            array(
              'type' => 'hongo_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => esc_html__( 'No padding in column', 'hongo-addons'),
              'param_name' => 'no_column_padding',
              'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
              'description' => esc_html__( 'If On then this column default padding of left and right will be removed.', 'hongo-addons' ),
            ),
            array(
              'type' => 'hongo_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => esc_html__( 'Position relative', 'hongo-addons'),
              'param_name' => 'position_relative',
              'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'hongo_overflow_type', 
              'heading' => esc_html__( 'Overflow', 'hongo-addons' ),
              'value' => array(esc_html__('Select', 'hongo-addons') => '',
                               esc_html__('Overflow visible', 'hongo-addons') => 'overflow-visible',
                               esc_html__('Overflow hidden', 'hongo-addons') => 'overflow-hidden',
                               esc_html__('Overflow auto', 'hongo-addons') => 'overflow-auto',
                              ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Z-index', 'hongo-addons'),
                'param_name' => 'z_index',
                'value' => '',
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_clear_both',
              'heading' => esc_html__( 'Clear both for desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'Default', 'hongo-addons') => '',
                               esc_html__( 'Clear both', 'hongo-addons') => 'clear-both',
                               esc_html__( 'Clear none', 'hongo-addons') => 'clear-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
              'description' => esc_html__( 'Clear both will move down this column.', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_mini_clear_both',
              'heading' => esc_html__( 'Clear both for mini desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'Default', 'hongo-addons') => '',
                               esc_html__( 'Clear both', 'hongo-addons') => 'md-clear-both',
                               esc_html__( 'Clear none', 'hongo-addons') => 'md-clear-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'description' => esc_html__( 'Clear both will move down this column.', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'ipad_clear_both',
              'heading' => esc_html__( 'Clear both for tablet', 'hongo-addons' ),
              'value' => array(esc_html__( 'Default', 'hongo-addons') => '',
                               esc_html__( 'Clear both', 'hongo-addons') => 'sm-clear-both',
                               esc_html__( 'Clear none', 'hongo-addons') => 'sm-clear-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'description' => esc_html__( 'Clear both will move down this column.', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'mobile_clear_both',
              'heading' => esc_html__( 'Clear both for mobile', 'hongo-addons' ),
              'value' => array(esc_html__( 'Default', 'hongo-addons') => '',
                               esc_html__( 'Clear both', 'hongo-addons') => 'xs-clear-both',
                               esc_html__( 'Clear none', 'hongo-addons') => 'xs-clear-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'description' => esc_html__( 'Clear both will move down this column.', 'hongo-addons' ),
            ),
            array(
              'type' => 'animation_style',
              'heading' => esc_html__( 'Animation', 'hongo-addons' ),
              'param_name' => 'hongo_column_animation_style',
              'value' => '',
              'settings' => array(
                'type' => array(
                  'in',
                  'other',
                ),
              ),
              'description' => __( 'Select type of animation for element to be animated when it "enters" the browsers viewport (Note: works only in modern browsers).', 'hongo-addons' ),
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Animation delay', 'hongo-addons' ),
              'param_name' => 'hongo_column_animation_delay',
              'dependency' => array( 'element' => 'hongo_column_animation_style', 'value_not_equal_to' => array( 'none' ) ),
              'description' => esc_html__( 'Add animation delay in mls, like 200', 'hongo-addons' ),
              'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Animation duration', 'hongo-addons' ),
              'param_name' => 'hongo_column_animation_duration',
              'dependency' => array( 'element' => 'hongo_column_animation_style', 'value_not_equal_to' => array( 'none' ) ),
              'description' => esc_html__( 'Add animation duration in mls, like 200', 'hongo-addons' ),
              'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_alignment',
              'heading' => esc_html__( 'Alignment in desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'No align', 'hongo-addons') => '',
                               esc_html__( 'Left align', 'hongo-addons') => 'text-left',
                               esc_html__( 'Right align', 'hongo-addons') => 'text-right',
                               esc_html__( 'Center align', 'hongo-addons') => 'text-center',
                               esc_html__( 'Justify align', 'hongo-addons') => 'text-justify',
                              ),
              'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_mini_alignment',
              'heading' => esc_html__( 'Alignment in mini desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'No align', 'hongo-addons') => '',
                               esc_html__( 'Left align', 'hongo-addons') => 'md-text-left',
                               esc_html__( 'Right align', 'hongo-addons') => 'md-text-right',
                               esc_html__( 'Center align', 'hongo-addons') => 'md-text-center',
                               esc_html__( 'Justify align', 'hongo-addons') => 'md-text-justify',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'ipad_alignment',
              'heading' => esc_html__( 'Alignment in tablet', 'hongo-addons' ),
              'value' => array(esc_html__( 'No align', 'hongo-addons') => '',
                               esc_html__( 'Left align', 'hongo-addons') => 'sm-text-left',
                               esc_html__( 'Right align', 'hongo-addons') => 'sm-text-right',
                               esc_html__( 'Center align', 'hongo-addons') => 'sm-text-center',
                               esc_html__( 'Justify align', 'hongo-addons') => 'sm-text-justify',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'mobile_alignment',
              'heading' => esc_html__( 'Alignment in mobile', 'hongo-addons' ),
              'value' => array(esc_html__( 'No align', 'hongo-addons') => '',
                               esc_html__( 'Left align', 'hongo-addons') => 'xs-text-left',
                               esc_html__( 'Right align', 'hongo-addons') => 'xs-text-right',
                               esc_html__( 'Center align', 'hongo-addons') => 'xs-text-center',
                               esc_html__( 'Justify align', 'hongo-addons') => 'xs-text-justify',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_display',
              'heading' => esc_html__( 'Display in desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'Select', 'hongo-addons') => '',
                               esc_html__( 'Block', 'hongo-addons') => 'display-block',
                               esc_html__( 'Inline', 'hongo-addons') => 'display-inline',
                               esc_html__( 'Inline block', 'hongo-addons') => 'display-inline-block',
                               esc_html__( 'None', 'hongo-addons') => 'display-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'desktop_mini_display',
              'heading' => esc_html__( 'Display in mini desktop', 'hongo-addons' ),
              'value' => array(esc_html__( 'Select', 'hongo-addons') => '',
                               esc_html__( 'Block', 'hongo-addons') => 'md-display-block',
                               esc_html__( 'Inline', 'hongo-addons') => 'md-display-inline',
                               esc_html__( 'Inline block', 'hongo-addons') => 'md-display-inline-block',
                               esc_html__( 'None', 'hongo-addons') => 'md-display-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'ipad_display',
              'heading' => esc_html__( 'Display in tablet', 'hongo-addons' ),
              'value' => array(esc_html__( 'Select', 'hongo-addons') => '',
                               esc_html__( 'Block', 'hongo-addons') => 'sm-display-block',
                               esc_html__( 'Inline', 'hongo-addons') => 'sm-display-inline',
                               esc_html__( 'Inline block', 'hongo-addons') => 'sm-display-inline-block',
                               esc_html__( 'None', 'hongo-addons') => 'sm-display-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'mobile_display',
              'heading' => esc_html__( 'Display in mobile', 'hongo-addons' ),
              'value' => array(esc_html__( 'Select', 'hongo-addons') => '',
                               esc_html__( 'Block', 'hongo-addons') => 'xs-display-block',
                               esc_html__( 'Inline', 'hongo-addons') => 'xs-display-inline',
                               esc_html__( 'Inline block', 'hongo-addons') => 'xs-display-inline-block',
                               esc_html__( 'None', 'hongo-addons') => 'xs-display-none',
                              ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
              'type' => 'hongo_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => esc_html__( 'Overlay', 'hongo-addons'),
              'param_name' => 'show_overlay',
              'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
              'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
              'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
              'type' => 'colorpicker',
              'class' => '',
              'heading' => esc_html__( 'Overlay color', 'hongo-addons' ),
              'param_name' => 'hongo_row_overlay_color',
              'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'heading' => esc_html__( 'Overlay opacity', 'hongo-addons'),
              'param_name' => 'hongo_overlay_opacity',
              'admin_label' => true,
              'value' => array( esc_html__( 'No opacity','hongo-addons') => '',
                                '0.1'  => '0.1',
                                '0.2'  => '0.2',
                                '0.3'  => '0.3',
                                '0.4'  => '0.4',
                                '0.5'  => '0.5',
                                '0.6'  => '0.6',
                                '0.7'  => '0.7',
                                '0.8'  => '0.8',
                                '0.9'  => '0.9',
                                '1.0'  => '1.0',
                              ),
              'std' => '0.7',
              'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Z-index', 'hongo-addons'),
              'param_name' => 'hongo_z_index',
              'dependency' => array( 'element' => 'show_overlay', 'value' => array('1') ),
              'edit_field_class' => 'vc_col-sm-6',
              'group' => esc_html__( 'Overlay', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'heading' => esc_html__( 'SM width', 'hongo-addons' ),
              'param_name' => 'width',
              'value' => $hongo_vc_column,
              'group' => esc_html__( 'Responsive Options', 'hongo-addons' ),
              'description' => esc_html__( 'Select column width', 'hongo-addons' ),
            ),
            array(
              'type' => 'column_offset',
              'heading' => esc_html__( 'Responsiveness', 'hongo-addons' ),
              'param_name' => 'offset',
              'group' => esc_html__( 'Responsive Options', 'hongo-addons' ),
              'description' => esc_html__( 'Adjust column for different screen sizes. Control width, offset and visibility settings.', 'hongo-addons' ),
            ),
            array(
              'type' => 'css_editor',
              'heading' => esc_html__( 'CSS box', 'hongo-addons' ),
              'param_name' => 'css',
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'param_name' => 'hongo_bg_image_type', 
              'heading' => esc_html__( 'Background type', 'hongo-addons' ),
              'value' => array(esc_html__('Select background type', 'hongo-addons') => '',
                               esc_html__('Fix background', 'hongo-addons') => 'fix-background',
                               esc_html__('Cover background', 'hongo-addons') => 'cover-background',
                              ),
              'edit_field_class' => 'vc_col-sm-3 vc_column-with-padding',
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'type' => 'dropdown',
              'heading' => esc_html__( 'Background position', 'hongo-addons' ),
              'param_name' => 'desktop_bg_image_position',
              'value' => $hongo_desktop_bg_image_position,
              'edit_field_class' => 'vc_col-sm-3',
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Minimum height', 'hongo-addons' ),
              'param_name' => 'desktop_height',
              'value' => '',
              'edit_field_class' => 'vc_col-sm-3',
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'param_name' => 'hongo_custom_separator_heading', // all params must have a unique name
              'type' => 'hongo_custom_title', // this param type
              'value' => '', // your custom markup
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'type' => 'hongo_custom_switch_option',
              'holder' => 'div',
              'class' => '',
              'heading' => esc_html__( 'Enable responsive css box', 'hongo-addons'),
              'param_name' => 'hongo_enable_responsive_css',
              'value' => array(esc_html__( 'Off', 'hongo-addons') => '0', 
                               esc_html__( 'On', 'hongo-addons') => '1'
                              ),
              'description' => esc_html__( 'This will enable mini dekstop, tablet and mobile css options.', 'hongo-addons' ),
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
              'type' => 'responsive_css_editor',
              'heading' => esc_html__( 'Responsive css box', 'hongo-addons' ),
              'param_name' => 'responsive_css',
              'width' => 'no',
              'dependency' => array( 'element' => 'hongo_enable_responsive_css', 'value' => array('1') ),
              'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        ),
    )
);