<?php
/**
 * Shortcode Map For Blog
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Blog */
/*-----------------------------------------------------------------------------------*/

$blog_class = 'hongo_blog_'.time() . '-2-' . rand( 0, 100 );
$categories_data = hongo_post_category_array();
vc_map( 
    array(
        'name' => esc_html__( 'Blog List', 'hongo-addons' ),
        'description' => esc_html__( 'Publish blog posts', 'hongo-addons' ),
        'icon' => 'hongo-shortcode-icon fa-solid fa-grip-horizontal',
        'base' => 'hongo_blog',
        'category' => 'Hongo',
        'params' => array(
            array(
                'type' => 'hidden',
                'heading' => esc_html__( 'Text', 'hongo-addons' ),
                'param_name' => 'hongo_token_class',
                'value' => $blog_class,
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons' ),
                'param_name' => 'hongo_blog_premade_style',
                'admin_label' => true,
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( 'Side Image', 'hongo-addons' ) => 'blog-side-image',
                    esc_html__( 'Masonry', 'hongo-addons' ) => 'blog-masonry',
                    esc_html__( 'Grid', 'hongo-addons' ) => 'blog-grid',
                    esc_html__( 'Clean', 'hongo-addons' ) => 'blog-clean',
                    esc_html__( 'Modern', 'hongo-addons' ) => 'blog-modern',
                    esc_html__( 'Only text', 'hongo-addons' ) => 'blog-only-text',
                    esc_html__( 'Overlay Image', 'hongo-addons' ) => 'blog-overlay-image',
                    esc_html__( 'Blog Image', 'hongo-addons' ) => 'blog-image',
                    esc_html__( 'Blog Standard', 'hongo-addons' ) => 'blog-standard',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__( 'Select pre-made style', 'hongo-addons' ),
                'param_name' => 'hongo_blog_preview_image',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'No. of columns', 'hongo-addons' ),
                'param_name' => 'hongo_blog_column',
                'std' => '3',
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( '1 columns', 'hongo-addons' ) => '1',
                    esc_html__( '2 columns', 'hongo-addons' ) => '2',
                    esc_html__( '3 columns', 'hongo-addons' ) => '3',
                    esc_html__( '4 columns', 'hongo-addons' ) => '4',
                    esc_html__( '5 columns', 'hongo-addons' ) => '5',
                    esc_html__( '6 columns', 'hongo-addons' ) => '6',
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image', 'blog-masonry', 'blog-grid', 'blog-clean', 'blog-modern', 'blog-only-text', 'blog-overlay-image', 'blog-image' ) ),
                'edit_field_class' => 'vc_col-sm-6',
            ),        
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Spacing between columns', 'hongo-addons' ),
                'param_name' => 'hongo_blog_type',
                'value' => array( 
                    esc_html__( 'Gutter default', 'hongo-addons' ) => '',
                    esc_html__( 'Gutter none', 'hongo-addons' ) => 'gutter-none',
                    esc_html__( 'Gutter very small', 'hongo-addons') => 'gutter-very-small',
                    esc_html__( 'Gutter small', 'hongo-addons') => 'gutter-small',
                    esc_html__( 'Gutter medium', 'hongo-addons') => 'gutter-medium',
                    esc_html__( 'Gutter large', 'hongo-addons') => 'gutter-large',
                    esc_html__( 'Gutter extra large', 'hongo-addons') => 'gutter-extra-large',
                ),
                'std' => 'gutter-medium',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image', 'blog-masonry', 'blog-grid', 'blog-clean', 'blog-modern', 'blog-only-text', 'blog-overlay-image', 'blog-image' ) ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Filter', 'hongo-addons' ),
                'param_name' => 'hongo_show_filter',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image', 'blog-overlay-image', 'blog-masonry', 'blog-grid', 'blog-clean', 'blog-modern', 'blog-only-text', 'blog-image', 'blog-standard' ) ),
            ),
            array(
                'type' => 'hongo_multiple_select_dropdown', // hongo_multiple_select_option
                'heading' => esc_html__( 'Categories', 'hongo-addons' ),
                'param_name' => 'hongo_categories_list',
                'value' => $categories_data,
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'No. of posts per page', 'hongo-addons' ),
                'param_name' => 'hongo_post_per_page',
                'value'     => '12',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
            ),
            array(
                'type' => 'animation_style',
                'heading' => esc_html__( 'Animation', 'hongo-addons' ),
                'param_name' => 'hongo_animation_style',
                'value' => '',
                'settings' => array(
                    'type' => array(
                        'in',
                        'other',
                    ),
                ),                
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'description' => __( 'Select type of animation for element to be animated when it "enters" the browsers viewport (Note: works only in modern browsers).', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Animation delay', 'hongo-addons' ),
                'param_name' => 'hongo_animation_delay',
                'dependency' => array( 'element' => 'hongo_animation_style', 'value_not_equal_to' => array( 'none' ) ),
                'description' => esc_html__( 'Add animation delay in mls, like 200', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',                
            ),
            array(
              'type' => 'textfield',
              'heading' => esc_html__( 'Animation duration', 'hongo-addons' ),
              'param_name' => 'hongo_animation_duration',
              'dependency' => array( 'element' => 'hongo_animation_style', 'value_not_equal_to' => array( 'none' ) ),
              'description' => esc_html__( 'Add animation duration in mls, like 200', 'hongo-addons' ),
              'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Pagination', 'hongo-addons' ),
                'param_name' => 'hongo_show_pagination',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Pagination style', 'hongo-addons' ),
                'param_name' => 'hongo_blog_pagination_style',
                'value' => array( 
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( 'Number pagination', 'hongo-addons' ) => 'number-pagination',
                    esc_html__( 'Infinite scroll', 'hongo-addons' ) => 'infinite-scroll-pagination',
                    esc_html__( 'Load more button', 'hongo-addons' ) => 'load-more-pagination',
                ),
                'std' => 'number-pagination',
                'dependency'  => array( 'element' => 'hongo_show_pagination', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post thumbnail', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_thumbnail',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                    ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-standard','blog-side-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-overlay-image','blog-image' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post featured image only', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_format',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'description' => esc_html__( 'If Off is selected then it will display block as per post format type like audio, video, gallery, etc… otherwise it will show post featured image no matter what is post format type.', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-standard' ) ),
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Post thumbnail size', 'hongo-addons' ),
                'param_name' => 'hongo_image_srcset',
                'value' => hongo_get_thumbnail_image_sizes(),
                'std' => 'hongo-medium-image',
                'dependency'  => array( 'element' => 'hongo_show_post_thumbnail', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post type icon', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_thumbnail_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                    ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-overlay-image','blog-image' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post title', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Separator', 'hongo-addons' ),
                'param_name' => 'hongo_show_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post author', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_author',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post author image', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_author_image',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '0',
                'dependency'  => array( 'element' => 'hongo_show_post_author', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post date', 'hongo-addons' ),
                'param_name' => 'hongo_show_post_date',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Post date format', 'hongo-addons' ),
                'param_name'  => 'hongo_date_format',
                'description' => wp_kses( 'Date format should be like F j, Y, <a target="_blank" href="https://codex.wordpress.org/Formatting_Date_and_Time">click here</a> to see other date formats.', 'hongo-addons' ),
                'value'       => 'd F Y',
                'dependency'  => array( 'element' => 'hongo_show_post_date', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post excerpt', 'hongo-addons' ),
                'param_name' => 'hongo_show_excerpt',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std'         => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Excerpt length', 'hongo-addons' ),
                'param_name'  => 'hongo_excerpt_length',
                'value'     => '18',
                'dependency'  => array( 'element' => 'hongo_show_excerpt', 'value' => array('1') ),
                'description' => esc_html__( 'Length in words', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post full content', 'hongo-addons' ),
                'param_name' => 'hongo_show_content',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std'         => '1',
                'dependency'  => array( 'element' => 'hongo_show_excerpt', 'value' => array('0') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post categories', 'hongo-addons' ),
                'param_name' => 'hongo_show_category',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std'         => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post likes', 'hongo-addons' ),
                'param_name' => 'hongo_show_like',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Post comments', 'hongo-addons' ),
                'param_name' => 'hongo_show_comment',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Read more button', 'hongo-addons' ),
                'param_name' => 'hongo_show_button',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type'        => 'textfield',
                'heading'     => esc_html__( 'Button text', 'hongo-addons' ),
                'param_name'  => 'hongo_button_text',
                'dependency'  => array( 'element' => 'hongo_show_button', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Posts order by', 'hongo-addons' ),
                'param_name' => 'hongo_orderby',
                'std' => 'date',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( 'Date', 'hongo-addons' ) => 'date',
                    esc_html__( 'ID', 'hongo-addons' ) => 'ID',
                    esc_html__( 'Author', 'hongo-addons' ) => 'author',
                    esc_html__( 'Title', 'hongo-addons' ) => 'title',
                    esc_html__( 'Modified', 'hongo-addons' ) => 'modified',
                    esc_html__( 'Random', 'hongo-addons' ) => 'rand',
                    esc_html__( 'Comment count', 'hongo-addons' ) => 'comment_count',
                    esc_html__( 'Menu order', 'hongo-addons' ) => 'menu_order',
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Posts sort by', 'hongo-addons' ),
                'param_name' => 'hongo_order',
                'std' => 'DESC',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( 'Descending', 'hongo-addons' ) => 'DESC',
                    esc_html__( 'Ascending', 'hongo-addons' ) => 'ASC',
                ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image','blog-overlay-image','blog-masonry','blog-grid','blog-clean','blog-modern','blog-only-text','blog-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
              	'type' => 'hongo_custom_switch_option',
              	'heading' => esc_html__( 'Image effect on hover', 'hongo-addons' ),
              	'param_name' => 'enable_image_zoom_effect',
              	'value' => array(esc_html__( 'Off', 'hongo-addons' ) => '0', 
                               esc_html__( 'On', 'hongo-addons' ) => '1'
                              ),
              	'std' => '1',
              	'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-masonry','blog-grid','blog-clean','blog-modern','blog-image' ) ),
              	'edit_field_class' => 'vc_col-sm-6',
               	'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
              	'type' => 'hongo_custom_switch_option',
              	'heading' => esc_html__( 'Hover icon', 'hongo-addons' ),
              	'param_name' => 'hongo_hide_icon',
              	'value' => array(esc_html__( 'Off', 'hongo-addons' ) => '0', 
                               esc_html__( 'On', 'hongo-addons' ) => '1'
                              ),
              	'std' => '1',
              	'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-clean' ) ),
              	'edit_field_class' => 'vc_col-sm-6',
               	'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Box border', 'hongo-addons' ),
                'param_name' => 'hongo_box_enable_border',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-only-text','blog-overlay-image','blog-standard' ) ),
                'edit_field_class' => 'vc_col-sm-6',
               	'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Box shadow', 'hongo-addons' ),
                'param_name' => 'hongo_box_enable_shadow',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons' ) => '0', 
                    esc_html__( 'On', 'hongo-addons' ) => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-only-text' ) ),
                'edit_field_class' => 'vc_col-sm-6',
               	'group' => esc_html__( 'Settings', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Show all categories filter', 'hongo-addons'),
                'param_name' => 'hongo_show_all_categories_filter',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'description' => esc_html__( 'Select On to show filter above blog', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array( '1' ) ),
                'group' => esc_html__( 'Filter', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_multiple_select_dropdown', // hongo_multiple_select_option
                'heading' => esc_html__( 'Filter categories', 'hongo-addons' ),
                'param_name' => 'hongo_main_categories_list',
                'value' => $categories_data,
                'group' => esc_html__( 'Filter', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array( '1' ) ),
                'description' => esc_html__('If you want to see different filter option than select category option here.', 'hongo-addons'),
            ),
            array(
                'type' => 'hongo_multiple_select_dropdown',
                'heading' => esc_html__( 'Default / selected filter category', 'hongo-addons'),
                'param_name' => 'hongo_default_category_selected',    
                'multiple' => false,
                'value'    => $categories_data,
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array( '1' ) ),
                'group' => esc_html__( 'Filter', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'All filter text', 'hongo-addons'),
                'param_name' => 'hongo_show_all_text',
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array('1') ),
                'std' => esc_html__( 'All', 'hongo-addons' ),
                'group' => esc_html__( 'Filter', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active filter color', 'hongo-addons' ),
                'param_name' => 'hongo_active_filter_color',
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Active filter border color', 'hongo-addons' ),
                'param_name' => 'hongo_active_filter_border_color',
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array('1') ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Hover overlay opacity', 'hongo-addons' ),
                'param_name' => 'hongo_blog_opacity',
                'value' => array(
                	esc_html__( 'Default', 'hongo-addons' ) => '',
                    esc_html__( 'No opacity', 'hongo-addons' ) => '0.0',
                    esc_html__( '0.1', 'hongo-addons' ) => '0.1',
                    esc_html__( '0.2', 'hongo-addons' ) => '0.2',
                    esc_html__( '0.3', 'hongo-addons' ) => '0.3',
                    esc_html__( '0.4', 'hongo-addons' ) => '0.4',
                    esc_html__( '0.5', 'hongo-addons' ) => '0.5',
                    esc_html__( '0.6', 'hongo-addons' ) => '0.6',
                    esc_html__( '0.7', 'hongo-addons' ) => '0.7',
                    esc_html__( '0.8', 'hongo-addons' ) => '0.8',
                    esc_html__( '0.9', 'hongo-addons' ) => '0.9',
                    esc_html__( '1.0', 'hongo-addons' ) => '1.0',
                ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'std' => '0.7',
                'edit_field_class' => 'vc_col-sm-6',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-modern', 'blog-overlay-image', 'blog-image' ) ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Hover overlay color', 'hongo-addons' ),
                'param_name' => 'hongo_overlay_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-modern', 'blog-overlay-image', 'blog-image' ) ),
                'edit_field_class' => 'vc_col-sm-6',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Category background color', 'hongo-addons' ),
                'param_name' => 'hongo_category_bg_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-masonry','blog-only-text','blog-clean', 'blog-image' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Category hover background color', 'hongo-addons' ),
                'param_name' => 'hongo_category_hover_bg_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-image' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Category border color', 'hongo-addons' ),
                'param_name' => 'hongo_category_border_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-image' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Category hover border color', 'hongo-addons' ),
                'param_name' => 'hongo_category_hover_border_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-image' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background color', 'hongo-addons' ),
                'param_name' => 'hongo_box_bg_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-masonry','blog-modern','blog-only-text','blog-overlay-image', 'blog-standard' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background hover color', 'hongo-addons' ),
                'param_name' => 'hongo_box_bg_hover_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array('blog-only-text') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'hongo_box_border_type',
                'heading' => esc_html__( 'Box border type', 'hongo-addons' ),
                'value' => array(
                    esc_html__( 'Default', 'hongo-addons' ) => '',
                    esc_html__( 'Dotted', 'hongo-addons' ) => 'dotted',
                    esc_html__( 'Dashed', 'hongo-addons' ) => 'dashed',
                    esc_html__( 'Solid', 'hongo-addons' ) =>  'solid',
                ),
                'dependency'  => array( 'element' => 'hongo_box_enable_border', 'value' => array('1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box border color', 'hongo-addons' ),
                'param_name' => 'hongo_box_border_color',
                'dependency'  => array( 'element' => 'hongo_box_enable_border', 'value' => array('1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Box border thickness', 'hongo-addons' ),
                'param_name' => 'hongo_box_border_size',
                'dependency'  => array( 'element' => 'hongo_box_enable_border', 'value' => array('1') ),
                'description' => esc_html__( 'In pixel like 1px', 'hongo-addons' ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Separator color', 'hongo-addons' ),
                'param_name' => 'hongo_separator_color',
                'dependency' => array( 'element' => 'hongo_show_separator', 'value' => array('1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'heading' => esc_html__( 'Arrow background color', 'hongo-addons' ),
                'param_name' => 'hongo_arrow_background_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-overlay-image', 'blog-clean' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'colorpicker',
                'heading' => esc_html__( 'Arrow color', 'hongo-addons' ),
                'param_name' => 'hongo_arrow_color',
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-overlay-image', 'blog-clean' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Separator thickness', 'hongo-addons' ),
                'param_name' => 'hongo_separator_height',
                'dependency' => array( 'element' => 'hongo_show_separator', 'value' => array('1') ),
                'description' => esc_html__( 'In pixel like 1px', 'hongo-addons' ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6',
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_title_setting',
                'heading'     => esc_html__( 'Title typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_post_title', 'value' => array('1') ),
                'hide_element_keys' => array( 'text-align' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_meta_setting',
                'heading'     => esc_html__( 'Post meta typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image', 'blog-overlay-image', 'blog-masonry', 'blog-grid', 'blog-clean', 'blog-modern', 'blog-only-text', 'blog-image', 'blog-standard' ) ),
                'hide_element_keys' => array( 'text-align' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_content_setting',
                'heading'     => esc_html__( 'Content typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_blog_premade_style', 'value' => array( 'blog-side-image', 'blog-overlay-image', 'blog-masonry', 'blog-grid', 'blog-clean', 'blog-modern', 'blog-only-text', 'blog-image', 'blog-standard' ) ),
                'hide_element_keys' => array( 'text-hover-color', 'text-align' ),
            ),
            array(
                'type'        => 'responsive_font_settings',
                'param_name'  => 'hongo_font_filter_setting',
                'heading'     => esc_html__( 'Filter typography', 'hongo-addons' ),
                'group' => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_filter', 'value' => array('1') ),
                'hide_element_keys' => array( 'text-align' ),
            ),
            array(
                'type'        => 'hongo_button_settings',
                'param_name'  => 'hongo_button_setting',
                'heading'     => esc_html__( 'Button typography', 'hongo-addons' ),                
                'group' => esc_html__( 'Button Setting', 'hongo-addons' ),
                'dependency' => array( 'element' => 'hongo_show_button', 'value' => array('1') ),
                'hide_element_keys' => array( 'text-decoration', 'icon-color', 'icon-hover-color' ),
            ),
            $hongo_vc_extra_id,
            $hongo_vc_extra_class,
        ),
    ) 
);