<?php
/**
 * Shortcode Map For Feature Box
 *
 * @package Hongo
 */
?>
<?php
/*-----------------------------------------------------------------------------------*/
/* Feature Box */
/*-----------------------------------------------------------------------------------*/

vc_map( 
  	array(
	    'name' => esc_html__( 'Features Box', 'hongo-addons'),
	    'description' => esc_html__( 'Features content blocks', 'hongo-addons'),
	    'icon' => 'fa-solid fa-info hongo-shortcode-icon',
	    'base' => 'hongo_pfeature_box',
	    'category' => 'Hongo',
	    'params' => array(
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Style', 'hongo-addons'),
                'admin_label' => true,
                'param_name' => 'hongo_product_feature_type',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Icon text style 1', 'hongo-addons')  => 'hongo-product-featurebox-2',
                    esc_html__( 'Icon text style 2', 'hongo-addons')  => 'hongo-product-featurebox-4',
                    esc_html__( 'Icon text style 3', 'hongo-addons')  => 'hongo-product-featurebox-3',
                    esc_html__( 'Icon text style 4', 'hongo-addons')  => 'icon-text-style-4',
                    esc_html__( 'Icon text style 5', 'hongo-addons')  => 'icon-text-style-5',
                    esc_html__( 'Icon text style 6', 'hongo-addons')  => 'icon-text-style-6',
                    esc_html__( 'Icon text style 7', 'hongo-addons')  => 'icon-text-style-7',
                    esc_html__( 'Icon text style 8', 'hongo-addons')  => 'icon-text-style-8',
                    esc_html__( 'Icon text style 9', 'hongo-addons')  => 'hongo-product-featurebox-1',
                    esc_html__( 'Icon text style 10', 'hongo-addons')  => 'icon-text-style-10',
                    esc_html__( 'Icon text style 11', 'hongo-addons')  => 'icon-text-style-11',
                    esc_html__( 'Custom icon text style 1', 'hongo-addons')  => 'custom-icon-text-style-1',
                    esc_html__( 'Fancy text box style 1', 'hongo-addons')  => 'fancy-text-box-style-1',
                    esc_html__( 'Fancy text box style 2', 'hongo-addons')  => 'fancy-text-box-style-2',
                    esc_html__( 'Fancy text box style 3', 'hongo-addons')  => 'fancy-text-box-style-3',
                    esc_html__( 'Fancy text box style 4', 'hongo-addons')  => 'fancy-text-box-style-4',
                    esc_html__( 'Fancy text box style 5', 'hongo-addons')  => 'fancy-text-box-style-5',
                    esc_html__( 'Fancy text box style 6', 'hongo-addons')  => 'fancy-text-box-style-6',
                    esc_html__( 'Text box style 1', 'hongo-addons')  => 'text-box-style-1',
                    esc_html__( 'Text box style 2', 'hongo-addons')  => 'text-box-style-2',
                    esc_html__( 'Text box style 3', 'hongo-addons')  => 'text-box-style-3',
                    esc_html__( 'Text box style 4', 'hongo-addons')  => 'text-box-style-4',
                    esc_html__( 'Rotate box style 1', 'hongo-addons')  => 'rotate-box-style-1',
                    esc_html__( 'Rotate box style 2', 'hongo-addons')  => 'rotate-box-style-2',
                    esc_html__( 'Rotate box style 3', 'hongo-addons')  => 'rotate-box-style-3',
                    esc_html__( 'Process step style 1', 'hongo-addons')  => 'process-step-style-1',
                    esc_html__( 'Process step style 2', 'hongo-addons')  => 'process-step-style-2',
                    esc_html__( 'Process step style 3', 'hongo-addons')  => 'process-step-style-3',
                    esc_html__( 'Info banner style 1', 'hongo-addons')  => 'info-banner-style-1',
                    esc_html__( 'Info banner style 2', 'hongo-addons')  => 'info-banner-style-2',
                    esc_html__( 'Info banner style 3', 'hongo-addons')  => 'info-banner-style-3',
                    esc_html__( 'Info banner style 4', 'hongo-addons')  => 'info-banner-style-4',
                    esc_html__( 'Info banner style 5', 'hongo-addons')  => 'info-banner-style-5',
                    esc_html__( 'Info banner style 6', 'hongo-addons')  => 'info-banner-style-6',
                    esc_html__( 'Interactive banner style 1', 'hongo-addons')  => 'interactive-banner-style-1',
                    esc_html__( 'Interactive banner style 2', 'hongo-addons')  => 'interactive-banner-style-2',
                    esc_html__( 'Interactive banner style 3', 'hongo-addons')  => 'interactive-banner-style-3',
                    esc_html__( 'Interactive banner style 4', 'hongo-addons')  => 'interactive-banner-style-4',
                    esc_html__( 'Interactive banner style 5', 'hongo-addons')  => 'interactive-banner-style-5',
                    esc_html__( 'Interactive banner style 6', 'hongo-addons')  => 'interactive-banner-style-6',
                ),
            ),
            array(
                'type' => 'hongo_preview_image',
                'heading' => esc_html__( 'Select pre-made style for Feature', 'hongo-addons'),
                'param_name' => 'hongo_product_feature_type_box_preview_image',              
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Equal height disable', 'hongo-addons'),
                'param_name' => 'equal_height_disable',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '0',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'hongo-product-featurebox-2','hongo-product-featurebox-4','icon-text-style-4','icon-text-style-10','icon-text-style-5','icon-text-style-6','icon-text-style-11','icon-text-style-7','icon-text-style-8','hongo-product-featurebox-1','hongo-product-featurebox-3','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6', 'text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2', 'interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6' )),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Custom icon image', 'hongo-addons'),
                'param_name' => 'custom_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'hongo-product-featurebox-1','hongo-product-featurebox-2','hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','text-box-style-1','text-box-style-2','text-box-style-3','rotate-box-style-2','rotate-box-style-3','process-step-style-2' )),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Icon background', 'hongo-addons'),
                'param_name' => 'icon_background',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'icon-text-style-5' ) ),
            ),
            array(
                'type' => 'attach_image',
                'heading' => esc_html__( 'Custom image', 'hongo-addons'),
                'param_name' => 'custom_icon_image',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '1' ),
                'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Extra Medium - 40px X 40px, Medium - 35px X 35px, Small - 24px X 24px, Extra Small - 16px X 16px', 'hongo-addons' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Icon image maximum width', 'hongo-addons' ),
                'param_name' => 'custom_icon_max_width',
                'value' => '',
                'dependency'  => array( 'element' => 'custom_icon', 'value' => array( '1' ) ),
                'description' => esc_html__( 'In pixel like 40px.', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__( 'Font icon', 'hongo-addons'),
                'param_name' => 'hongo_icon_list',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
            ),
            array(
                'type' => 'attach_image',
                'heading' => esc_html__( 'Image / Hover image', 'hongo-addons'),
                'param_name' => 'hongo_featurebox_image',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-4','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Image thumbnail size', 'hongo-addons' ),
                'param_name' => 'hongo_featurebox_image_srcset',
                'value' => hongo_get_thumbnail_image_sizes(),
                'std' => 'full',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-4','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Image position', 'hongo-addons'),
                'param_name' => 'hongo_image_position',                
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons') => '',
                    esc_html__( 'Top', 'hongo-addons') => 'top',
                    esc_html__( 'Bottom', 'hongo-addons') => 'bottom',
                ),
                'std' => 'top',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-3' )),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Number', 'hongo-addons' ),
                'param_name' => 'hongo_feature_number',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'fancy-text-box-style-1','fancy-text-box-style-6','text-box-style-4','process-step-style-1' ,'process-step-style-3','interactive-banner-style-5') ),
            ),
            array(
            	'type' => 'textfield',
            	'heading' => esc_html__( 'Title', 'hongo-addons' ),
            	'param_name' => 'hongo_feature_title',
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6')),
            	'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Title custom icon', 'hongo-addons'),
                'param_name' => 'title_custom_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0',
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'interactive-banner-style-1','interactive-banner-style-2','info-banner-style-4' )),
            ),
            array(
                'type' => 'attach_image',
                'heading' => esc_html__( 'Title custom icon image', 'hongo-addons'),
                'param_name' => 'title_custom_icon_image',
                'dependency' => array( 'element' => 'title_custom_icon', 'value' => '1' ),
                'description' => esc_html__( 'Recommended size: Extra Large - 60px X 60px, Large - 50px X 50px, Extra Medium - 40px X 40px, Medium - 35px X 35px, Small - 24px X 24px, Extra Small - 16px X 16px', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__( 'Title font icon', 'hongo-addons'),
                'param_name' => 'title_hongo_icon_list',
                'admin_label' => true,
                'dependency' => array( 'element' => 'title_custom_icon', 'value' => '0' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Hover title', 'hongo-addons' ),
                'param_name' => 'hongo_feature_hover_title',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('interactive-banner-style-1','interactive-banner-style-3')),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
            	'type' => 'textfield',
            	'heading' => esc_html__( 'Subtitle', 'hongo-addons' ),
            	'param_name' => 'hongo_feature_subtitle',
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-4','fancy-text-box-style-5','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-6')),
                'description' => esc_html__( 'Use || to break the word in new line.', 'hongo-addons' ),
            ),
            array(
                'type' => 'textarea',
                'heading' => esc_html__( 'Content', 'hongo-addons' ),
                'param_name' => 'hongo_feature_content',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4')),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Phone', 'hongo-addons' ),
                'param_name' => 'hongo_feature_phone',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-4' ) ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Email', 'hongo-addons' ),
                'param_name' => 'hongo_feature_email',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-4' ) ),
            ),
            array(
                'type'        => 'vc_link',
                'heading'     => esc_html__('Button configuration', 'hongo-addons' ),
                'param_name'  => 'hongo_button_config',
                'admin_label' => true,
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('rotate-box-style-3','icon-text-style-6','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-6') ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'class' => '',
                'heading' => esc_html__( 'Button icon / image', 'hongo-addons'),
                'param_name' => 'hongo_button_enable_icon',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('rotate-box-style-3','icon-text-style-6','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-6') ),
            ),            
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button icon size', 'hongo-addons'),
                'param_name' => 'hongo_button_icon_type',
                'value' => array(
                    esc_html__('Select Icon Size', 'hongo-addons') => '',
                    esc_html__('Extra Large', 'hongo-addons') => 'icon-extra-large',
                    esc_html__('Large', 'hongo-addons') => 'icon-large',
                    esc_html__('Extra Medium', 'hongo-addons') => 'icon-extra-medium',
                    esc_html__('Medium', 'hongo-addons') => 'icon-medium',
                    esc_html__('Extra Small', 'hongo-addons') => 'icon-extra-small',
                    esc_html__('Small', 'hongo-addons') => 'icon-small',
                    esc_html__('Very Small', 'hongo-addons') => 'icon-very-small',
                ),
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => '1' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button icon position', 'hongo-addons'),
                'param_name' => 'hongo_button_icon_position',
                'value' => array(
                    esc_html__('Left', 'hongo-addons') => 'left',
                    esc_html__('Right', 'hongo-addons') => 'right',
                ),
                'std' => 'left',
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => array( '1' ) ),
            ),
            array(
                'type' => 'hongo_icon',
                'heading' => esc_html__('Button font icon', 'hongo-addons'),
                'param_name' => 'hongo_button_icon',
                'admin_label' => true,
                'dependency' => array( 'element' => 'hongo_button_enable_icon', 'value' => '1' ),
            ),
            array(
            	'type' => 'hongo_custom_switch_option',
            	'heading' => esc_html__( 'Link on text', 'hongo-addons'),
            	'param_name' => 'hongo_enable_link',
            	'value' => array(
            		esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6')),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Link target', 'hongo-addons'),
                'param_name' => 'hongo_link_target',
                'value' => array(
                    esc_html__('Self', 'hongo-addons') => '_self', 
                    esc_html__('New tab / window', 'hongo-addons') => '_blank'
                ),
                'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Add link on', 'hongo-addons'),
                'param_name' => 'hongo_link_on',
                'admin_label' => true,
                'value' => array(
                    esc_html__( 'Select','hongo-addons') => '',
                    esc_html__( 'Icon / Number','hongo-addons') => 'icon',
                    esc_html__( 'Title','hongo-addons') => 'title',
                    esc_html__( 'All','hongo-addons') => 'all',
                ),    
                'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Link / URL', 'hongo-addons'),
                'param_name' => 'hongo_link_url',
                'admin_label' => true,
                'dependency'  => array( 'element' => 'hongo_enable_link', 'value' => '1' ),
                'description' => esc_html__( 'Enter full URL with http, like http://www.example.com', 'hongo-addons' ),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Desktop right separator', 'hongo-addons'),
                'param_name' => 'hongo_desktop_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'process-step-style-1','process-step-style-2','process-step-style-3')),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Mini desktop right separator', 'hongo-addons'),
                'param_name' => 'hongo_mini_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'process-step-style-1','process-step-style-2','process-step-style-3')),
            ),            
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Ipad right separator', 'hongo-addons'),
                'param_name' => 'hongo_ipad_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'process-step-style-1','process-step-style-2','process-step-style-3')),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Mobile right separator', 'hongo-addons'),
                'param_name' => 'hongo_mobile_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'process-step-style-1','process-step-style-2','process-step-style-3')),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box background color', 'hongo-addons'),
                'param_name' => 'hongo_product_feature_box_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','info-banner-style-1','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','process-step-style-2','icon-text-style-8','fancy-text-box-style-3','fancy-text-box-style-5','interactive-banner-style-1', 'interactive-banner-style-5','rotate-box-style-2', 'icon-text-style-10', 'icon-text-style-11' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box border color', 'hongo-addons'),
                'param_name' => 'hongo_product_feature_box_border_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-1' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Box border thickness', 'hongo-addons' ),
                'param_name' => 'hongo_product_feature_box_border_width',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('info-banner-style-1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'description' => esc_html__( 'In pixel like 2px', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box gradient color', 'hongo-addons'),
                'param_name' => 'hongo_product_feature_box_gradient_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box hover background color', 'hongo-addons'),
                'param_name' => 'hongo_product_feature_box_hover_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','info-banner-style-2','fancy-text-box-style-2','fancy-text-box-style-4','fancy-text-box-style-5','rotate-box-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-6','fancy-text-box-style-3', 'rotate-box-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box hover gradient background color', 'hongo-addons'),
                'param_name' => 'hongo_feature_box_hover_gradient_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('fancy-text-box-style-5','rotate-box-style-1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Box hover border color', 'hongo-addons'),
                'param_name' => 'hongo_box_hover_border_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('info-banner-style-2') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'textfield',
                'heading' => esc_html__( 'Box hover border thickness', 'hongo-addons' ),
                'param_name' => 'hongo_box_hover_border_width',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('info-banner-style-2') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'description' => esc_html__( 'In pixel like 2px', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Title Background Color', 'hongo-addons'),
                'param_name' => 'hongo_title_bg_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('rotate-box-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Subtitle Background Color', 'hongo-addons'),
                'param_name' => 'hongo_subtitle_bg_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('info-banner-style-5') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Enable separator', 'hongo-addons'),
                'param_name' => 'hongo_enable_separator',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'hongo-product-featurebox-2','icon-text-style-8','fancy-text-box-style-5', 'rotate-box-style-1','info-banner-style-4')),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Separator color', 'hongo-addons' ),
                'param_name' => 'hongo_separator_color',
                'dependency' => array( 'element' => 'hongo_enable_separator', 'value' => '1' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Right separator color', 'hongo-addons' ),
                'param_name' => 'hongo_right_separator_color',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'process-step-style-1','process-step-style-2','process-step-style-3')),
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon Background color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_bg_color',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('icon-text-style-5', 'rotate-box-style-3','interactive-banner-style-2')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_color',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Icon hover color', 'hongo-addons' ),
                'param_name' => 'hongo_icon_hover_color',
                'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
            	'type' => 'dropdown',
            	'heading' => esc_html__( 'Icon size', 'hongo-addons'),
            	'param_name' => 'hongo_icon_size',
            	'admin_label' => true,
            	'value' => array(
                    esc_html__( 'Default', 'hongo-addons') => '',
                    esc_html__( 'Extra large', 'hongo-addons') => 'icon-extra-large', 
                    esc_html__( 'Large', 'hongo-addons') => 'icon-large',
                    esc_html__( 'Extra medium', 'hongo-addons') => 'icon-extra-medium',
                    esc_html__( 'Medium', 'hongo-addons') => 'icon-medium',
                    esc_html__( 'Small', 'hongo-addons') => 'icon-small',
                    esc_html__( 'Extra small', 'hongo-addons') => 'icon-extra-small',
                ),
            	'dependency' => array( 'element' => 'custom_icon', 'value' => '0' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            	'group' => esc_html__( 'Style', 'hongo-addons' ),
            ),
            array(
            	'type' => 'colorpicker',
            	'class' => '',
            	'heading' => esc_html__( 'Title icon color', 'hongo-addons' ),
            	'param_name' => 'hongo_title_icon_color',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'interactive-banner-style-1','interactive-banner-style-2','info-banner-style-4' )),
            	'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),            
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number border color', 'hongo-addons'),
                'param_name' => 'hongo_number_border_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('fancy-text-box-style-1','text-box-style-4','process-step-style-1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number hover border color', 'hongo-addons'),
                'param_name' => 'hongo_number_hover_border_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-4','process-step-style-1') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number color', 'hongo-addons'),
                'param_name' => 'hongo_number_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('fancy-text-box-style-1','fancy-text-box-style-6','text-box-style-4','process-step-style-1', 'interactive-banner-style-5', 'process-step-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number hover color', 'hongo-addons'),
                'param_name' => 'hongo_number_hover_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-4','process-step-style-1', 'process-step-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number background color', 'hongo-addons'),
                'param_name' => 'hongo_hover_bg_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-4','process-step-style-1', 'process-step-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'colorpicker',
                'class' => '',
                'heading' => esc_html__( 'Number hover background color', 'hongo-addons'),
                'param_name' => 'hongo_number_hover_bg_color',
                'dependency' => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-4','process-step-style-1', 'process-step-style-3') ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_width',
                'heading' => esc_html__( 'Content width in desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_width,
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-3','icon-text-style-7','icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','text-box-style-1','interactive-banner-style-2', 'process-step-style-1', 'process-step-style-2', 'process-step-style-3', 'interactive-banner-style-2', 'interactive-banner-style-3', 'interactive-banner-style-4')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_desktop_mini_width',
                'heading' => esc_html__( 'Content width in mini desktop', 'hongo-addons' ),
                'value' => $hongo_desktop_mini_width,
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-3','icon-text-style-7','icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','text-box-style-1','interactive-banner-style-2', 'process-step-style-1', 'process-step-style-2', 'process-step-style-3', 'interactive-banner-style-2', 'interactive-banner-style-3', 'interactive-banner-style-4' ) ),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_ipad_width',
                'heading' => esc_html__( 'Content width in tablet', 'hongo-addons' ),
                'value' => $hongo_ipad_width,
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-3','icon-text-style-7','icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','text-box-style-1','interactive-banner-style-2', 'process-step-style-1', 'process-step-style-2', 'process-step-style-3', 'interactive-banner-style-2', 'interactive-banner-style-3', 'interactive-banner-style-4')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'param_name' => 'content_mobile_width',
                'heading' => esc_html__( 'Content width in mobile', 'hongo-addons' ),
                'value' => $hongo_mobile_width,
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-3','icon-text-style-7','icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','text-box-style-1','interactive-banner-style-2', 'process-step-style-1', 'process-step-style-2', 'process-step-style-3', 'interactive-banner-style-2', 'interactive-banner-style-3', 'interactive-banner-style-4')),
                'group' => esc_html__( 'Style', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding',
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__('Button style', 'hongo-addons'),
                'param_name' => 'hongo_button_style',
                'value' => array(
                    esc_html__( 'Default', 'hongo-addons' ) => '',
                    esc_html__( 'Black', 'hongo-addons' ) => 'style1',
                    esc_html__( 'White', 'hongo-addons' ) => 'style2',
                    esc_html__( 'Base color', 'hongo-addons' ) => 'style10',
                    esc_html__( 'Black border', 'hongo-addons' ) => 'style3',
                    esc_html__( 'White border', 'hongo-addons' ) => 'style4',
                    esc_html__( 'Base color border', 'hongo-addons' ) => 'style11',
                    esc_html__( 'Black round corner', 'hongo-addons' ) => 'style5',
                    esc_html__( 'White round corner', 'hongo-addons' ) => 'style6',
                    esc_html__( 'Base color round corner', 'hongo-addons' ) => 'style12',
                    esc_html__( 'Black border with rounded', 'hongo-addons' ) => 'style7',
                    esc_html__( 'White border with rounded', 'hongo-addons' ) => 'style8',
                    esc_html__( 'Base color border with rounded', 'hongo-addons' ) => 'style13',
                    esc_html__( 'Text with underline', 'hongo-addons' ) => 'style9',
                    esc_html__( 'Base color text with underline', 'hongo-addons' ) => 'style14',
                ),
                'admin_label' => true,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding button-style-setting',
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('rotate-box-style-3','icon-text-style-6','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-6') ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Button size', 'hongo-addons' ),
                'param_name' => 'hongo_button_type',
                'value' => array(
                    esc_html__( 'Select', 'hongo-addons' ) => '',
                    esc_html__( 'Extra large', 'hongo-addons' ) => 'extra-large',
                    esc_html__( 'Large', 'hongo-addons' ) => 'large',
                    esc_html__( 'Medium', 'hongo-addons' ) => 'medium',
                    esc_html__( 'Small', 'hongo-addons' ) => 'small',
                    esc_html__( 'Very small', 'hongo-addons' ) => 'vsmall',
                ),
                'group' => esc_html__( 'Button Settings', 'hongo-addons' ),
                'edit_field_class' => 'vc_col-sm-6 button-style-setting',
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'rotate-box-style-3','icon-text-style-6','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-6' ) ),
            ),
            array(
                'type'       => 'hongo_button_settings',
                'param_name' => 'hongo_button_setting',
                'heading'    => esc_html__( 'Button typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Button Settings', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'rotate-box-style-3', 'icon-text-style-6', 'info-banner-style-1', 'info-banner-style-2', 'info-banner-style-3', 'info-banner-style-5', 'info-banner-style-6', 'interactive-banner-style-1', 'interactive-banner-style-3', 'interactive-banner-style-4', 'interactive-banner-style-6' ) ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_number_setting',
                'heading'    => esc_html__( 'Number typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'fancy-text-box-style-1','fancy-text-box-style-6' ,'text-box-style-4','process-step-style-1','process-step-style-3') ),  
                'hide_element_keys' => array( 'text-color', 'text-hover-color', 'font-transform', 'text-align' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_title_setting',
                'heading'    => esc_html__( 'Title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6')),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Title element tag', 'hongo-addons'),
                'param_name' => 'title_heading_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6')),
            ),     
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description' => esc_html__( 'If On is selected then title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','info-banner-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6')),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_hover_title_setting',
                'heading'    => esc_html__( 'Hover title typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('fancy-text-box-style-3','interactive-banner-style-1','interactive-banner-style-3')),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for hover title', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_hover_title',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'std' => '1',
                'edit_field_class' => 'vc_col-sm-12 vc_column-with-padding typography-left-setting typography-full-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description' => esc_html__( 'If On is selected then hover title will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('interactive-banner-style-1','interactive-banner-style-3')),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_subtitle_setting',
                'heading'    => esc_html__( 'Subtitle typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3', 'icon-text-style-4', 'icon-text-style-10','fancy-text-box-style-1','fancy-text-box-style-4','fancy-text-box-style-5','info-banner-style-3','info-banner-style-5','info-banner-style-6' ,'icon-text-style-8','interactive-banner-style-6' )),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type' => 'dropdown',
                'heading' => esc_html__( 'Subtitle element tag', 'hongo-addons'),
                'param_name' => 'subtitle_heading_tag',
                'value' => $hongo_element_tag,
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-left-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3', 'icon-text-style-4', 'icon-text-style-10','fancy-text-box-style-1','fancy-text-box-style-4','fancy-text-box-style-5','info-banner-style-3','info-banner-style-5','info-banner-style-6' ,'icon-text-style-8','interactive-banner-style-6' )),
            ),
            array(
                'type' => 'hongo_custom_switch_option',
                'heading' => esc_html__( 'Use additional font for subtitle', 'hongo-addons'),
                'param_name' => 'hongo_enable_alternate_font_subtitle',
                'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
                'edit_field_class' => 'vc_col-sm-6 vc_column-with-padding typography-right-setting',
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'description' => esc_html__( 'If On is selected then subtitle will use additional font family setup in WordPress customizer', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-3', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-4','fancy-text-box-style-5','info-banner-style-3','info-banner-style-5','info-banner-style-6','interactive-banner-style-6')),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_content_setting',
                'heading'    => esc_html__( 'Content typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-2','text-box-style-3','text-box-style-4','rotate-box-style-1','rotate-box-style-2','rotate-box-style-3','process-step-style-1','process-step-style-2','process-step-style-3','info-banner-style-1','info-banner-style-2','info-banner-style-3','info-banner-style-4','info-banner-style-5','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4')),
                'hide_element_keys' => array( 'text-hover-color' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_phone_setting',
                'heading'    => esc_html__( 'Phone typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-4' )),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform' ),
            ),
            array(
                'type'       => 'responsive_font_settings',
                'param_name' => 'hongo_font_email_setting',
                'heading'    => esc_html__( 'Email typography', 'hongo-addons' ),
                'group'      => esc_html__( 'Typography', 'hongo-addons' ),
                'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array( 'info-banner-style-4' )),
                'hide_element_keys' => array( 'text-hover-color', 'font-transform' ),
            ),
            array(
          		'type' => 'css_editor',
          		'heading' => esc_html__( 'CSS box', 'hongo-addons' ),
          		'param_name' => 'css',
          		'group' => esc_html__( 'Design Options', 'hongo-addons' ),
          		'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','interactive-banner-style-1','interactive-banner-style-2','interactive-banner-style-3','interactive-banner-style-4','interactive-banner-style-5','interactive-banner-style-6','text-box-style-1','text-box-style-3', 'info-banner-style-3','info-banner-style-5','info-banner-style-6')),
            ),
            array(
          		'type' => 'dropdown',
          	    'param_name' => 'hongo_bg_image_type', 
            	'heading' => esc_html__( 'Background type', 'hongo-addons' ),
            	'value' => array(
                    esc_html__('Select background type', 'hongo-addons') => '',
                    esc_html__('Fix background', 'hongo-addons') => 'fix-background',
                    esc_html__('Cover background', 'hongo-addons') => 'cover-background',
                ),
            	'edit_field_class' => 'vc_col-sm-4 vc_column-with-padding',
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-3', 'info-banner-style-3','info-banner-style-5', 'info-banner-style-6')),
            	'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            ),
            array(
            	'type' => 'dropdown',
            	'heading' => esc_html__( 'Background position', 'hongo-addons' ),
            	'param_name' => 'desktop_bg_image_position',
            	'value' => $hongo_desktop_bg_image_position,
            	'edit_field_class' => 'vc_col-sm-4',
            	'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-3', 'info-banner-style-3','info-banner-style-5', 'info-banner-style-6')),
            ),
            array(
            	'param_name' => 'hongo_custom_separator_heading',
            	'type' => 'hongo_custom_title',
            	'value' => '',
            	'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-3','info-banner-style-5', 'info-banner-style-6')),	
            ),
            array(
            	'type' => 'hongo_custom_switch_option',
            	'class' => '',
            	'heading' => esc_html__( 'Enable responsive css', 'hongo-addons'),
            	'param_name' => 'hongo_enable_responsive_css',
            	'value' => array(
                    esc_html__( 'Off', 'hongo-addons') => '0', 
                    esc_html__( 'On', 'hongo-addons') => '1'
                ),
            	'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            	'dependency'  => array( 'element' => 'hongo_product_feature_type', 'value' => array('hongo-product-featurebox-1', 'hongo-product-featurebox-2', 'hongo-product-featurebox-3', 'hongo-product-featurebox-4', 'icon-text-style-4', 'icon-text-style-10', 'icon-text-style-5', 'icon-text-style-6','icon-text-style-11', 'icon-text-style-7', 'icon-text-style-8','custom-icon-text-style-1','fancy-text-box-style-1','fancy-text-box-style-2','fancy-text-box-style-3','fancy-text-box-style-4','fancy-text-box-style-5','fancy-text-box-style-6','text-box-style-1','text-box-style-3', 'info-banner-style-3','info-banner-style-5','info-banner-style-6')),
            ),
            array(
            	'type' => 'responsive_css_editor',
            	'heading' => esc_html__( 'Responsive css box', 'hongo-addons' ),
            	'param_name' => 'responsive_css',
            	//'height' => 'no',
            	'width' => 'no',
            	'group' => esc_html__( 'Design Options', 'hongo-addons' ),
            	'dependency' => array( 'element' => 'hongo_enable_responsive_css', 'value' => array('1') ),
            ),
	        $hongo_vc_extra_id,
	      	$hongo_vc_extra_class,
	    ),
    )
);

